# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gsdview/gdalbackend/ui/banddialog.ui'
#
# Created: Sun Nov 13 21:17:58 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_bandDialog(object):
    def setupUi(self, bandDialog):
        bandDialog.setObjectName(_fromUtf8("bandDialog"))
        bandDialog.resize(539, 519)
        bandDialog.setWindowTitle(QtGui.QApplication.translate("bandDialog", "GDAL Raster Band", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(bandDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(bandDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.infoTab = QtGui.QWidget()
        self.infoTab.setObjectName(_fromUtf8("infoTab"))
        self.infoTabVerticalLayout = QtGui.QVBoxLayout(self.infoTab)
        self.infoTabVerticalLayout.setContentsMargins(-1, -1, -1, 12)
        self.infoTabVerticalLayout.setObjectName(_fromUtf8("infoTabVerticalLayout"))
        self.infoGroupBox = QtGui.QGroupBox(self.infoTab)
        self.infoGroupBox.setTitle(QtGui.QApplication.translate("bandDialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.infoGroupBox.setObjectName(_fromUtf8("infoGroupBox"))
        self.infoHorizontalLayout = QtGui.QHBoxLayout(self.infoGroupBox)
        self.infoHorizontalLayout.setObjectName(_fromUtf8("infoHorizontalLayout"))
        self.infoGridLayout = QtGui.QGridLayout()
        self.infoGridLayout.setObjectName(_fromUtf8("infoGridLayout"))
        self.descriptionLabel = QtGui.QLabel(self.infoGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionLabel.sizePolicy().hasHeightForWidth())
        self.descriptionLabel.setSizePolicy(sizePolicy)
        self.descriptionLabel.setText(QtGui.QApplication.translate("bandDialog", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.infoGridLayout.addWidget(self.descriptionLabel, 0, 0, 1, 1)
        self.descriptionValue = QtGui.QLabel(self.infoGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionValue.sizePolicy().hasHeightForWidth())
        self.descriptionValue.setSizePolicy(sizePolicy)
        self.descriptionValue.setText(QtGui.QApplication.translate("bandDialog", "description value", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.descriptionValue.setObjectName(_fromUtf8("descriptionValue"))
        self.infoGridLayout.addWidget(self.descriptionValue, 0, 1, 1, 1)
        self.bandNumberLabel = QtGui.QLabel(self.infoGroupBox)
        self.bandNumberLabel.setText(QtGui.QApplication.translate("bandDialog", "Band Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.bandNumberLabel.setObjectName(_fromUtf8("bandNumberLabel"))
        self.infoGridLayout.addWidget(self.bandNumberLabel, 1, 0, 1, 1)
        self.bandNumberValue = QtGui.QLabel(self.infoGroupBox)
        self.bandNumberValue.setToolTip(QtGui.QApplication.translate("bandDialog", "Fetch the band number. ", None, QtGui.QApplication.UnicodeUTF8))
        self.bandNumberValue.setText(QtGui.QApplication.translate("bandDialog", "band number value", None, QtGui.QApplication.UnicodeUTF8))
        self.bandNumberValue.setObjectName(_fromUtf8("bandNumberValue"))
        self.infoGridLayout.addWidget(self.bandNumberValue, 1, 1, 1, 1)
        self.colorInterpretationLabel = QtGui.QLabel(self.infoGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorInterpretationLabel.sizePolicy().hasHeightForWidth())
        self.colorInterpretationLabel.setSizePolicy(sizePolicy)
        self.colorInterpretationLabel.setText(QtGui.QApplication.translate("bandDialog", "Color Interpretation:", None, QtGui.QApplication.UnicodeUTF8))
        self.colorInterpretationLabel.setObjectName(_fromUtf8("colorInterpretationLabel"))
        self.infoGridLayout.addWidget(self.colorInterpretationLabel, 2, 0, 1, 1)
        self.colorInterpretationValue = QtGui.QLabel(self.infoGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorInterpretationValue.sizePolicy().hasHeightForWidth())
        self.colorInterpretationValue.setSizePolicy(sizePolicy)
        self.colorInterpretationValue.setToolTip(QtGui.QApplication.translate("bandDialog", "How should this band be interpreted as color?\n"
"\n"
"CV_Undefined is returned when the format doesn\'t know anything about the\n"
"color interpretation.", None, QtGui.QApplication.UnicodeUTF8))
        self.colorInterpretationValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "How should this band be interpreted as color?\n"
"\n"
"CV_Undefined is returned when the format doesn\'t know anything about the\n"
"color interpretation.", None, QtGui.QApplication.UnicodeUTF8))
        self.colorInterpretationValue.setText(QtGui.QApplication.translate("bandDialog", "color interpretation value", None, QtGui.QApplication.UnicodeUTF8))
        self.colorInterpretationValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.colorInterpretationValue.setObjectName(_fromUtf8("colorInterpretationValue"))
        self.infoGridLayout.addWidget(self.colorInterpretationValue, 2, 1, 1, 1)
        self.overviewCountValue = QtGui.QLabel(self.infoGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overviewCountValue.sizePolicy().hasHeightForWidth())
        self.overviewCountValue.setSizePolicy(sizePolicy)
        self.overviewCountValue.setText(QtGui.QApplication.translate("bandDialog", "overview count value", None, QtGui.QApplication.UnicodeUTF8))
        self.overviewCountValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.overviewCountValue.setObjectName(_fromUtf8("overviewCountValue"))
        self.infoGridLayout.addWidget(self.overviewCountValue, 3, 1, 1, 1)
        self.overviewCountLabel = QtGui.QLabel(self.infoGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overviewCountLabel.sizePolicy().hasHeightForWidth())
        self.overviewCountLabel.setSizePolicy(sizePolicy)
        self.overviewCountLabel.setText(QtGui.QApplication.translate("bandDialog", "Overview Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.overviewCountLabel.setObjectName(_fromUtf8("overviewCountLabel"))
        self.infoGridLayout.addWidget(self.overviewCountLabel, 3, 0, 1, 1)
        self.hasArbitraryOverviewsLabel = QtGui.QLabel(self.infoGroupBox)
        self.hasArbitraryOverviewsLabel.setText(QtGui.QApplication.translate("bandDialog", "Has Arbitrary Overviews:", None, QtGui.QApplication.UnicodeUTF8))
        self.hasArbitraryOverviewsLabel.setObjectName(_fromUtf8("hasArbitraryOverviewsLabel"))
        self.infoGridLayout.addWidget(self.hasArbitraryOverviewsLabel, 4, 0, 1, 1)
        self.hasArbitraryOverviewsValue = QtGui.QLabel(self.infoGroupBox)
        self.hasArbitraryOverviewsValue.setText(QtGui.QApplication.translate("bandDialog", "has arbitrary overviews value", None, QtGui.QApplication.UnicodeUTF8))
        self.hasArbitraryOverviewsValue.setObjectName(_fromUtf8("hasArbitraryOverviewsValue"))
        self.infoGridLayout.addWidget(self.hasArbitraryOverviewsValue, 4, 1, 1, 1)
        self.infoHorizontalLayout.addLayout(self.infoGridLayout)
        spacerItem = QtGui.QSpacerItem(118, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.infoHorizontalLayout.addItem(spacerItem)
        self.infoTabVerticalLayout.addWidget(self.infoGroupBox)
        self.dataGroupBox = QtGui.QGroupBox(self.infoTab)
        self.dataGroupBox.setTitle(QtGui.QApplication.translate("bandDialog", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGroupBox.setObjectName(_fromUtf8("dataGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dataGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dataGridLayoutLeft = QtGui.QGridLayout()
        self.dataGridLayoutLeft.setObjectName(_fromUtf8("dataGridLayoutLeft"))
        self.xSizeLabel = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xSizeLabel.sizePolicy().hasHeightForWidth())
        self.xSizeLabel.setSizePolicy(sizePolicy)
        self.xSizeLabel.setText(QtGui.QApplication.translate("bandDialog", "X Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.xSizeLabel.setObjectName(_fromUtf8("xSizeLabel"))
        self.dataGridLayoutLeft.addWidget(self.xSizeLabel, 0, 0, 1, 1)
        self.xSizeValue = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xSizeValue.sizePolicy().hasHeightForWidth())
        self.xSizeValue.setSizePolicy(sizePolicy)
        self.xSizeValue.setText(QtGui.QApplication.translate("bandDialog", "x size value", None, QtGui.QApplication.UnicodeUTF8))
        self.xSizeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.xSizeValue.setObjectName(_fromUtf8("xSizeValue"))
        self.dataGridLayoutLeft.addWidget(self.xSizeValue, 0, 1, 1, 1)
        self.ySizeLabel = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ySizeLabel.sizePolicy().hasHeightForWidth())
        self.ySizeLabel.setSizePolicy(sizePolicy)
        self.ySizeLabel.setText(QtGui.QApplication.translate("bandDialog", "Y Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.ySizeLabel.setObjectName(_fromUtf8("ySizeLabel"))
        self.dataGridLayoutLeft.addWidget(self.ySizeLabel, 1, 0, 1, 1)
        self.ySizeValue = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ySizeValue.sizePolicy().hasHeightForWidth())
        self.ySizeValue.setSizePolicy(sizePolicy)
        self.ySizeValue.setText(QtGui.QApplication.translate("bandDialog", "y size value", None, QtGui.QApplication.UnicodeUTF8))
        self.ySizeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ySizeValue.setObjectName(_fromUtf8("ySizeValue"))
        self.dataGridLayoutLeft.addWidget(self.ySizeValue, 1, 1, 1, 1)
        self.blockSizeLabel = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockSizeLabel.sizePolicy().hasHeightForWidth())
        self.blockSizeLabel.setSizePolicy(sizePolicy)
        self.blockSizeLabel.setText(QtGui.QApplication.translate("bandDialog", "Block Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.blockSizeLabel.setObjectName(_fromUtf8("blockSizeLabel"))
        self.dataGridLayoutLeft.addWidget(self.blockSizeLabel, 2, 0, 1, 1)
        self.blockSizeValue = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockSizeValue.sizePolicy().hasHeightForWidth())
        self.blockSizeValue.setSizePolicy(sizePolicy)
        self.blockSizeValue.setToolTip(QtGui.QApplication.translate("bandDialog", "The \"natural\" block size of this band.\n"
"\n"
"GDAL contains a concept of the natural block size of rasters so that\n"
"applications can organized data access efficiently for some file formats.\n"
"The natural block size is the block size that is most efficient for accessing\n"
"the format. For many formats this is simple a whole scanline in which case\n"
"*pnXSize is set to GetXSize(), and *pnYSize is set to 1.\n"
"\n"
"However, for tiled images this will typically be the tile size.\n"
"\n"
"Note that the X and Y block sizes don\'t have to divide the image size evenly,\n"
"\n"
"meaning that right and bottom edge blocks may be incomplete.\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.blockSizeValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "The \"natural\" block size of this band.\n"
"\n"
"GDAL contains a concept of the natural block size of rasters so that\n"
"applications can organized data access efficiently for some file formats.\n"
"The natural block size is the block size that is most efficient for accessing\n"
"the format. For many formats this is simple a whole scanline in which case\n"
"*pnXSize is set to GetXSize(), and *pnYSize is set to 1.\n"
"\n"
"However, for tiled images this will typically be the tile size.\n"
"\n"
"Note that the X and Y block sizes don\'t have to divide the image size evenly,\n"
"\n"
"meaning that right and bottom edge blocks may be incomplete.\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.blockSizeValue.setText(QtGui.QApplication.translate("bandDialog", "block size value", None, QtGui.QApplication.UnicodeUTF8))
        self.blockSizeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.blockSizeValue.setObjectName(_fromUtf8("blockSizeValue"))
        self.dataGridLayoutLeft.addWidget(self.blockSizeValue, 2, 1, 1, 1)
        self.noDataLabel = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noDataLabel.sizePolicy().hasHeightForWidth())
        self.noDataLabel.setSizePolicy(sizePolicy)
        self.noDataLabel.setText(QtGui.QApplication.translate("bandDialog", "No Data Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.noDataLabel.setObjectName(_fromUtf8("noDataLabel"))
        self.dataGridLayoutLeft.addWidget(self.noDataLabel, 3, 0, 1, 1)
        self.noDataValue = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noDataValue.sizePolicy().hasHeightForWidth())
        self.noDataValue.setSizePolicy(sizePolicy)
        self.noDataValue.setToolTip(QtGui.QApplication.translate("bandDialog", "The no data value for this band.\n"
"\n"
"If there is no out of data value, an out of range value will generally be returned.\n"
"The no data value for a band is generally a special marker value used to mark\n"
"pixels that are not valid data. Such pixels should generally not be displayed,\n"
"nor contribute to analysis operations.", None, QtGui.QApplication.UnicodeUTF8))
        self.noDataValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "The no data value for this band.\n"
"\n"
"If there is no out of data value, an out of range value will generally be returned.\n"
"The no data value for a band is generally a special marker value used to mark\n"
"pixels that are not valid data. Such pixels should generally not be displayed,\n"
"nor contribute to analysis operations.", None, QtGui.QApplication.UnicodeUTF8))
        self.noDataValue.setText(QtGui.QApplication.translate("bandDialog", "no data value", None, QtGui.QApplication.UnicodeUTF8))
        self.noDataValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.noDataValue.setObjectName(_fromUtf8("noDataValue"))
        self.dataGridLayoutLeft.addWidget(self.noDataValue, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.dataGridLayoutLeft)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.dataGridLayoutRight = QtGui.QGridLayout()
        self.dataGridLayoutRight.setObjectName(_fromUtf8("dataGridLayoutRight"))
        self.offsetLabel = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetLabel.sizePolicy().hasHeightForWidth())
        self.offsetLabel.setSizePolicy(sizePolicy)
        self.offsetLabel.setText(QtGui.QApplication.translate("bandDialog", "Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetLabel.setObjectName(_fromUtf8("offsetLabel"))
        self.dataGridLayoutRight.addWidget(self.offsetLabel, 2, 0, 1, 1)
        self.offsetValue = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetValue.sizePolicy().hasHeightForWidth())
        self.offsetValue.setSizePolicy(sizePolicy)
        self.offsetValue.setToolTip(QtGui.QApplication.translate("bandDialog", "The raster value offset.\n"
"\n"
"This value (in combination with the GetScale() value) is used to transform\n"
"raw pixel values into the units returned by GetUnits().\n"
"For example this might be used to store elevations in GUInt16 bands with\n"
"a precision of 0.1, and starting from -100.\n"
"\n"
"  Units value = (raw value * scale) + offset\n"
"\n"
"For file formats that don\'t know this intrinsically a value of zero is returned.\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "The raster value offset.\n"
"\n"
"This value (in combination with the GetScale() value) is used to transform\n"
"raw pixel values into the units returned by GetUnits().\n"
"For example this might be used to store elevations in GUInt16 bands with\n"
"a precision of 0.1, and starting from -100.\n"
"\n"
"  Units value = (raw value * scale) + offset\n"
"\n"
"For file formats that don\'t know this intrinsically a value of zero is returned.\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetValue.setText(QtGui.QApplication.translate("bandDialog", "offset value", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.offsetValue.setObjectName(_fromUtf8("offsetValue"))
        self.dataGridLayoutRight.addWidget(self.offsetValue, 2, 1, 1, 1)
        self.scaleLabel = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleLabel.sizePolicy().hasHeightForWidth())
        self.scaleLabel.setSizePolicy(sizePolicy)
        self.scaleLabel.setText(QtGui.QApplication.translate("bandDialog", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel.setObjectName(_fromUtf8("scaleLabel"))
        self.dataGridLayoutRight.addWidget(self.scaleLabel, 3, 0, 1, 1)
        self.scaleValue = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleValue.sizePolicy().hasHeightForWidth())
        self.scaleValue.setSizePolicy(sizePolicy)
        self.scaleValue.setText(QtGui.QApplication.translate("bandDialog", "scale value", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.scaleValue.setObjectName(_fromUtf8("scaleValue"))
        self.dataGridLayoutRight.addWidget(self.scaleValue, 3, 1, 1, 1)
        self.dataTypeLabel = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTypeLabel.sizePolicy().hasHeightForWidth())
        self.dataTypeLabel.setSizePolicy(sizePolicy)
        self.dataTypeLabel.setText(QtGui.QApplication.translate("bandDialog", "Data Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTypeLabel.setObjectName(_fromUtf8("dataTypeLabel"))
        self.dataGridLayoutRight.addWidget(self.dataTypeLabel, 0, 0, 1, 1)
        self.dataTypeValue = QtGui.QLabel(self.dataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTypeValue.sizePolicy().hasHeightForWidth())
        self.dataTypeValue.setSizePolicy(sizePolicy)
        self.dataTypeValue.setText(QtGui.QApplication.translate("bandDialog", "data type value", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTypeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.dataTypeValue.setObjectName(_fromUtf8("dataTypeValue"))
        self.dataGridLayoutRight.addWidget(self.dataTypeValue, 0, 1, 1, 1)
        self.unitTypeLabel = QtGui.QLabel(self.dataGroupBox)
        self.unitTypeLabel.setText(QtGui.QApplication.translate("bandDialog", "Unit Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.unitTypeLabel.setObjectName(_fromUtf8("unitTypeLabel"))
        self.dataGridLayoutRight.addWidget(self.unitTypeLabel, 1, 0, 1, 1)
        self.unitTypeValue = QtGui.QLabel(self.dataGroupBox)
        self.unitTypeValue.setText(QtGui.QApplication.translate("bandDialog", "unit type value", None, QtGui.QApplication.UnicodeUTF8))
        self.unitTypeValue.setObjectName(_fromUtf8("unitTypeValue"))
        self.dataGridLayoutRight.addWidget(self.unitTypeValue, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.dataGridLayoutRight)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.infoTabVerticalLayout.addWidget(self.dataGroupBox)
        self.imageStructureGroupBox = QtGui.QGroupBox(self.infoTab)
        self.imageStructureGroupBox.setTitle(QtGui.QApplication.translate("bandDialog", "Image Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.imageStructureGroupBox.setObjectName(_fromUtf8("imageStructureGroupBox"))
        self.imageStructureHorizontalLayout = QtGui.QHBoxLayout(self.imageStructureGroupBox)
        self.imageStructureHorizontalLayout.setObjectName(_fromUtf8("imageStructureHorizontalLayout"))
        self.imageStructureGridLayout = QtGui.QGridLayout()
        self.imageStructureGridLayout.setObjectName(_fromUtf8("imageStructureGridLayout"))
        self.compressionValue = QtGui.QLabel(self.imageStructureGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compressionValue.sizePolicy().hasHeightForWidth())
        self.compressionValue.setSizePolicy(sizePolicy)
        self.compressionValue.setToolTip(QtGui.QApplication.translate("bandDialog", "The compression type used for this dataset or band.\n"
"\n"
"There is no fixed catalog of compression type names, but where a given format includes a COMPRESSION creation option, the same list of values should be used here as there.", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "The compression type used for this dataset or band.\n"
"\n"
"There is no fixed catalog of compression type names, but where a given format includes a COMPRESSION creation option, the same list of values should be used here as there.", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionValue.setText(QtGui.QApplication.translate("bandDialog", "compression value", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.compressionValue.setObjectName(_fromUtf8("compressionValue"))
        self.imageStructureGridLayout.addWidget(self.compressionValue, 0, 1, 1, 1)
        self.nbitsLabel = QtGui.QLabel(self.imageStructureGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbitsLabel.sizePolicy().hasHeightForWidth())
        self.nbitsLabel.setSizePolicy(sizePolicy)
        self.nbitsLabel.setText(QtGui.QApplication.translate("bandDialog", "Numbero of bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.nbitsLabel.setObjectName(_fromUtf8("nbitsLabel"))
        self.imageStructureGridLayout.addWidget(self.nbitsLabel, 1, 0, 1, 1)
        self.nbitsValue = QtGui.QLabel(self.imageStructureGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbitsValue.sizePolicy().hasHeightForWidth())
        self.nbitsValue.setSizePolicy(sizePolicy)
        self.nbitsValue.setToolTip(QtGui.QApplication.translate("bandDialog", "The actual number of bits used for this band, or the bands of this dataset.\n"
"\n"
"Normally only present when the number of bits is non-standard for the datatype, such as when a 1 bit TIFF is represented through GDAL as GDT_Byte.", None, QtGui.QApplication.UnicodeUTF8))
        self.nbitsValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "The actual number of bits used for this band, or the bands of this dataset.\n"
"\n"
"Normally only present when the number of bits is non-standard for the datatype, such as when a 1 bit TIFF is represented through GDAL as GDT_Byte.", None, QtGui.QApplication.UnicodeUTF8))
        self.nbitsValue.setText(QtGui.QApplication.translate("bandDialog", "nbits value", None, QtGui.QApplication.UnicodeUTF8))
        self.nbitsValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.nbitsValue.setObjectName(_fromUtf8("nbitsValue"))
        self.imageStructureGridLayout.addWidget(self.nbitsValue, 1, 1, 1, 1)
        self.compressionLabel = QtGui.QLabel(self.imageStructureGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compressionLabel.sizePolicy().hasHeightForWidth())
        self.compressionLabel.setSizePolicy(sizePolicy)
        self.compressionLabel.setText(QtGui.QApplication.translate("bandDialog", "Compression:", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionLabel.setObjectName(_fromUtf8("compressionLabel"))
        self.imageStructureGridLayout.addWidget(self.compressionLabel, 0, 0, 1, 1)
        self.pixelTypeLabel = QtGui.QLabel(self.imageStructureGroupBox)
        self.pixelTypeLabel.setText(QtGui.QApplication.translate("bandDialog", "Pixel type:", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelTypeLabel.setObjectName(_fromUtf8("pixelTypeLabel"))
        self.imageStructureGridLayout.addWidget(self.pixelTypeLabel, 3, 0, 1, 1)
        self.interleaveLabel = QtGui.QLabel(self.imageStructureGroupBox)
        self.interleaveLabel.setText(QtGui.QApplication.translate("bandDialog", "Interleave:", None, QtGui.QApplication.UnicodeUTF8))
        self.interleaveLabel.setObjectName(_fromUtf8("interleaveLabel"))
        self.imageStructureGridLayout.addWidget(self.interleaveLabel, 2, 0, 1, 1)
        self.interleaveValue = QtGui.QLabel(self.imageStructureGroupBox)
        self.interleaveValue.setToolTip(QtGui.QApplication.translate("bandDialog", "This only applies on datasets, and the value should be one of PIXEL, LINE or BAND. It can be used as a data access hint.", None, QtGui.QApplication.UnicodeUTF8))
        self.interleaveValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "This only applies on datasets, and the value should be one of PIXEL, LINE or BAND. It can be used as a data access hint.", None, QtGui.QApplication.UnicodeUTF8))
        self.interleaveValue.setText(QtGui.QApplication.translate("bandDialog", "interleave value", None, QtGui.QApplication.UnicodeUTF8))
        self.interleaveValue.setObjectName(_fromUtf8("interleaveValue"))
        self.imageStructureGridLayout.addWidget(self.interleaveValue, 2, 1, 1, 1)
        self.pixelTypeValue = QtGui.QLabel(self.imageStructureGroupBox)
        self.pixelTypeValue.setToolTip(QtGui.QApplication.translate("bandDialog", "This may appear on a GDT_Byte band (or the corresponding dataset) and have the value SIGNEDBYTE to indicate the unsigned byte values between 128 and 255 should be interpreted as being values between -128 and -1 for applications that recognise the SIGNEDBYTE type.", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelTypeValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "This may appear on a GDT_Byte band (or the corresponding dataset) and have the value SIGNEDBYTE to indicate the unsigned byte values between 128 and 255 should be interpreted as being values between -128 and -1 for applications that recognise the SIGNEDBYTE type.", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelTypeValue.setText(QtGui.QApplication.translate("bandDialog", "pixel type value", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelTypeValue.setObjectName(_fromUtf8("pixelTypeValue"))
        self.imageStructureGridLayout.addWidget(self.pixelTypeValue, 3, 1, 1, 1)
        self.imageStructureHorizontalLayout.addLayout(self.imageStructureGridLayout)
        spacerItem3 = QtGui.QSpacerItem(211, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imageStructureHorizontalLayout.addItem(spacerItem3)
        self.infoTabVerticalLayout.addWidget(self.imageStructureGroupBox)
        spacerItem4 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.infoTabVerticalLayout.addItem(spacerItem4)
        self.tabWidget.addTab(self.infoTab, _fromUtf8(""))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.infoTab), QtGui.QApplication.translate("bandDialog", "Info about the raster band.", None, QtGui.QApplication.UnicodeUTF8))
        self.metadataTab = QtGui.QWidget()
        self.metadataTab.setObjectName(_fromUtf8("metadataTab"))
        self.metadataTabVerticalLayout = QtGui.QVBoxLayout(self.metadataTab)
        self.metadataTabVerticalLayout.setObjectName(_fromUtf8("metadataTabVerticalLayout"))
        self.tabWidget.addTab(self.metadataTab, _fromUtf8(""))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.metadataTab), QtGui.QApplication.translate("bandDialog", "Raster band metadata.", None, QtGui.QApplication.UnicodeUTF8))
        self.statisticsTab = QtGui.QWidget()
        self.statisticsTab.setObjectName(_fromUtf8("statisticsTab"))
        self.statisticsVerticalLayout = QtGui.QVBoxLayout(self.statisticsTab)
        self.statisticsVerticalLayout.setObjectName(_fromUtf8("statisticsVerticalLayout"))
        self.statisticsGroupBox = QtGui.QGroupBox(self.statisticsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statisticsGroupBox.sizePolicy().hasHeightForWidth())
        self.statisticsGroupBox.setSizePolicy(sizePolicy)
        self.statisticsGroupBox.setTitle(QtGui.QApplication.translate("bandDialog", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.statisticsGroupBox.setObjectName(_fromUtf8("statisticsGroupBox"))
        self.statisticsHorizontalLayout = QtGui.QHBoxLayout(self.statisticsGroupBox)
        self.statisticsHorizontalLayout.setObjectName(_fromUtf8("statisticsHorizontalLayout"))
        self.statisticsFormLayout = QtGui.QFormLayout()
        self.statisticsFormLayout.setObjectName(_fromUtf8("statisticsFormLayout"))
        self.minimumLabel = QtGui.QLabel(self.statisticsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimumLabel.sizePolicy().hasHeightForWidth())
        self.minimumLabel.setSizePolicy(sizePolicy)
        self.minimumLabel.setText(QtGui.QApplication.translate("bandDialog", "Minimum:", None, QtGui.QApplication.UnicodeUTF8))
        self.minimumLabel.setObjectName(_fromUtf8("minimumLabel"))
        self.statisticsFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.minimumLabel)
        self.minimumValue = QtGui.QLabel(self.statisticsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimumValue.sizePolicy().hasHeightForWidth())
        self.minimumValue.setSizePolicy(sizePolicy)
        self.minimumValue.setToolTip(QtGui.QApplication.translate("bandDialog", "The minimum value for this band.\n"
"\n"
"For file formats that don\'t know this intrinsically, the minimum supported\n"
"value for the data type will generally be returned (or None).", None, QtGui.QApplication.UnicodeUTF8))
        self.minimumValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "The minimum value for this band.\n"
"\n"
"For file formats that don\'t know this intrinsically, the minimum supported\n"
"value for the data type will generally be returned (or None).", None, QtGui.QApplication.UnicodeUTF8))
        self.minimumValue.setText(QtGui.QApplication.translate("bandDialog", "minimum value", None, QtGui.QApplication.UnicodeUTF8))
        self.minimumValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.minimumValue.setObjectName(_fromUtf8("minimumValue"))
        self.statisticsFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.minimumValue)
        self.maximumLabel = QtGui.QLabel(self.statisticsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximumLabel.sizePolicy().hasHeightForWidth())
        self.maximumLabel.setSizePolicy(sizePolicy)
        self.maximumLabel.setText(QtGui.QApplication.translate("bandDialog", "Maximum:", None, QtGui.QApplication.UnicodeUTF8))
        self.maximumLabel.setObjectName(_fromUtf8("maximumLabel"))
        self.statisticsFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.maximumLabel)
        self.maximumValue = QtGui.QLabel(self.statisticsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximumValue.sizePolicy().hasHeightForWidth())
        self.maximumValue.setSizePolicy(sizePolicy)
        self.maximumValue.setToolTip(QtGui.QApplication.translate("bandDialog", "The maximum value for this band.\n"
"\n"
"For file formats that don\'t know this intrinsically, the maximum supported\n"
"value for the data type will generally be returned (or None).", None, QtGui.QApplication.UnicodeUTF8))
        self.maximumValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "The maximum value for this band.\n"
"\n"
"For file formats that don\'t know this intrinsically, the maximum supported\n"
"value for the data type will generally be returned (or None).", None, QtGui.QApplication.UnicodeUTF8))
        self.maximumValue.setText(QtGui.QApplication.translate("bandDialog", "maximum value", None, QtGui.QApplication.UnicodeUTF8))
        self.maximumValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.maximumValue.setObjectName(_fromUtf8("maximumValue"))
        self.statisticsFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.maximumValue)
        self.meanLabel = QtGui.QLabel(self.statisticsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meanLabel.sizePolicy().hasHeightForWidth())
        self.meanLabel.setSizePolicy(sizePolicy)
        self.meanLabel.setText(QtGui.QApplication.translate("bandDialog", "Mean:", None, QtGui.QApplication.UnicodeUTF8))
        self.meanLabel.setObjectName(_fromUtf8("meanLabel"))
        self.statisticsFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.meanLabel)
        self.meanValue = QtGui.QLabel(self.statisticsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meanValue.sizePolicy().hasHeightForWidth())
        self.meanValue.setSizePolicy(sizePolicy)
        self.meanValue.setToolTip(QtGui.QApplication.translate("bandDialog", "The maximum value for this band.\n"
"\n"
"For file formats that don\'t know this intrinsically, the maximum supported\n"
"value for the data type will generally be returned (or None).", None, QtGui.QApplication.UnicodeUTF8))
        self.meanValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "The maximum value for this band.\n"
"\n"
"For file formats that don\'t know this intrinsically, the maximum supported\n"
"value for the data type will generally be returned (or None).", None, QtGui.QApplication.UnicodeUTF8))
        self.meanValue.setText(QtGui.QApplication.translate("bandDialog", "mean value", None, QtGui.QApplication.UnicodeUTF8))
        self.meanValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.meanValue.setObjectName(_fromUtf8("meanValue"))
        self.statisticsFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.meanValue)
        self.stdLabel = QtGui.QLabel(self.statisticsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stdLabel.sizePolicy().hasHeightForWidth())
        self.stdLabel.setSizePolicy(sizePolicy)
        self.stdLabel.setText(QtGui.QApplication.translate("bandDialog", "Standard Deviation:", None, QtGui.QApplication.UnicodeUTF8))
        self.stdLabel.setObjectName(_fromUtf8("stdLabel"))
        self.statisticsFormLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.stdLabel)
        self.stdValue = QtGui.QLabel(self.statisticsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stdValue.sizePolicy().hasHeightForWidth())
        self.stdValue.setSizePolicy(sizePolicy)
        self.stdValue.setToolTip(QtGui.QApplication.translate("bandDialog", "The maximum value for this band.\n"
"\n"
"For file formats that don\'t know this intrinsically, the maximum supported\n"
"value for the data type will generally be returned (or None).", None, QtGui.QApplication.UnicodeUTF8))
        self.stdValue.setWhatsThis(QtGui.QApplication.translate("bandDialog", "The maximum value for this band.\n"
"\n"
"For file formats that don\'t know this intrinsically, the maximum supported\n"
"value for the data type will generally be returned (or None).", None, QtGui.QApplication.UnicodeUTF8))
        self.stdValue.setText(QtGui.QApplication.translate("bandDialog", "standard deviation value", None, QtGui.QApplication.UnicodeUTF8))
        self.stdValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.stdValue.setObjectName(_fromUtf8("stdValue"))
        self.statisticsFormLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.stdValue)
        self.statisticsHorizontalLayout.addLayout(self.statisticsFormLayout)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statisticsHorizontalLayout.addItem(spacerItem5)
        self.statButtondVerticalLayout = QtGui.QVBoxLayout()
        self.statButtondVerticalLayout.setObjectName(_fromUtf8("statButtondVerticalLayout"))
        self.approxStatsCheckBox = QtGui.QCheckBox(self.statisticsGroupBox)
        self.approxStatsCheckBox.setEnabled(False)
        self.approxStatsCheckBox.setToolTip(QtGui.QApplication.translate("bandDialog", "Compute approximate band statistics using\n"
"overviews or a subset of image tiles.", None, QtGui.QApplication.UnicodeUTF8))
        self.approxStatsCheckBox.setWhatsThis(QtGui.QApplication.translate("bandDialog", "Compute approximate band statistics using\n"
"overviews or a subset of image tiles.", None, QtGui.QApplication.UnicodeUTF8))
        self.approxStatsCheckBox.setText(QtGui.QApplication.translate("bandDialog", "Approx Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.approxStatsCheckBox.setChecked(True)
        self.approxStatsCheckBox.setObjectName(_fromUtf8("approxStatsCheckBox"))
        self.statButtondVerticalLayout.addWidget(self.approxStatsCheckBox)
        self.computeStatsButton = QtGui.QPushButton(self.statisticsGroupBox)
        self.computeStatsButton.setToolTip(QtGui.QApplication.translate("bandDialog", "Start band statistics computation\n"
"(may take a long time).", None, QtGui.QApplication.UnicodeUTF8))
        self.computeStatsButton.setText(QtGui.QApplication.translate("bandDialog", "Compute Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.computeStatsButton.setObjectName(_fromUtf8("computeStatsButton"))
        self.statButtondVerticalLayout.addWidget(self.computeStatsButton)
        self.dummyLabel = QtGui.QLabel(self.statisticsGroupBox)
        self.dummyLabel.setText(_fromUtf8(""))
        self.dummyLabel.setObjectName(_fromUtf8("dummyLabel"))
        self.statButtondVerticalLayout.addWidget(self.dummyLabel)
        self.statisticsHorizontalLayout.addLayout(self.statButtondVerticalLayout)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statisticsHorizontalLayout.addItem(spacerItem6)
        self.statisticsVerticalLayout.addWidget(self.statisticsGroupBox)
        self.histogramGroupBox = QtGui.QGroupBox(self.statisticsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogramGroupBox.sizePolicy().hasHeightForWidth())
        self.histogramGroupBox.setSizePolicy(sizePolicy)
        self.histogramGroupBox.setTitle(QtGui.QApplication.translate("bandDialog", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramGroupBox.setObjectName(_fromUtf8("histogramGroupBox"))
        self.histogramVericalLayout = QtGui.QVBoxLayout(self.histogramGroupBox)
        self.histogramVericalLayout.setObjectName(_fromUtf8("histogramVericalLayout"))
        self.histogramTableWidget = QtGui.QTableWidget(self.histogramGroupBox)
        self.histogramTableWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.histogramTableWidget.setObjectName(_fromUtf8("histogramTableWidget"))
        self.histogramTableWidget.setColumnCount(3)
        self.histogramTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("bandDialog", "Class Min", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("bandDialog", "Class Max", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("bandDialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramTableWidget.setHorizontalHeaderItem(2, item)
        self.histogramTableWidget.horizontalHeader().setStretchLastSection(True)
        self.histogramVericalLayout.addWidget(self.histogramTableWidget)
        self.histogramHorizontalLayout = QtGui.QHBoxLayout()
        self.histogramHorizontalLayout.setObjectName(_fromUtf8("histogramHorizontalLayout"))
        self.customHistogramCheckBox = QtGui.QCheckBox(self.histogramGroupBox)
        self.customHistogramCheckBox.setToolTip(QtGui.QApplication.translate("bandDialog", "Pops up a dialog that allow to customize\n"
"the histogram computation.", None, QtGui.QApplication.UnicodeUTF8))
        self.customHistogramCheckBox.setText(QtGui.QApplication.translate("bandDialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.customHistogramCheckBox.setObjectName(_fromUtf8("customHistogramCheckBox"))
        self.histogramHorizontalLayout.addWidget(self.customHistogramCheckBox)
        self.computeHistogramButton = QtGui.QPushButton(self.histogramGroupBox)
        self.computeHistogramButton.setToolTip(QtGui.QApplication.translate("bandDialog", "Start histogram computation\n"
"(may take a long time).", None, QtGui.QApplication.UnicodeUTF8))
        self.computeHistogramButton.setText(QtGui.QApplication.translate("bandDialog", "Compute", None, QtGui.QApplication.UnicodeUTF8))
        self.computeHistogramButton.setObjectName(_fromUtf8("computeHistogramButton"))
        self.histogramHorizontalLayout.addWidget(self.computeHistogramButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.histogramHorizontalLayout.addItem(spacerItem7)
        self.numberOfClassesLabel = QtGui.QLabel(self.histogramGroupBox)
        self.numberOfClassesLabel.setText(QtGui.QApplication.translate("bandDialog", "Number of classes:", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfClassesLabel.setObjectName(_fromUtf8("numberOfClassesLabel"))
        self.histogramHorizontalLayout.addWidget(self.numberOfClassesLabel)
        self.numberOfClassesValue = QtGui.QLabel(self.histogramGroupBox)
        self.numberOfClassesValue.setText(QtGui.QApplication.translate("bandDialog", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfClassesValue.setObjectName(_fromUtf8("numberOfClassesValue"))
        self.histogramHorizontalLayout.addWidget(self.numberOfClassesValue)
        self.histogramVericalLayout.addLayout(self.histogramHorizontalLayout)
        self.statisticsVerticalLayout.addWidget(self.histogramGroupBox)
        self.statisticsVerticalLayout.setStretch(1, 10)
        self.tabWidget.addTab(self.statisticsTab, _fromUtf8(""))
        self.colorTableTab = QtGui.QWidget()
        self.colorTableTab.setObjectName(_fromUtf8("colorTableTab"))
        self.colorTabVerticalLayout = QtGui.QVBoxLayout(self.colorTableTab)
        self.colorTabVerticalLayout.setObjectName(_fromUtf8("colorTabVerticalLayout"))
        self.colorHorizontalLayout = QtGui.QHBoxLayout()
        self.colorHorizontalLayout.setObjectName(_fromUtf8("colorHorizontalLayout"))
        self.colorFormLayout = QtGui.QFormLayout()
        self.colorFormLayout.setObjectName(_fromUtf8("colorFormLayout"))
        self.ctInterpretationLabel = QtGui.QLabel(self.colorTableTab)
        self.ctInterpretationLabel.setText(QtGui.QApplication.translate("bandDialog", "Color interpetation:", None, QtGui.QApplication.UnicodeUTF8))
        self.ctInterpretationLabel.setObjectName(_fromUtf8("ctInterpretationLabel"))
        self.colorFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ctInterpretationLabel)
        self.ctInterpretationValue = QtGui.QLabel(self.colorTableTab)
        self.ctInterpretationValue.setText(QtGui.QApplication.translate("bandDialog", "color interpretation value", None, QtGui.QApplication.UnicodeUTF8))
        self.ctInterpretationValue.setObjectName(_fromUtf8("ctInterpretationValue"))
        self.colorFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ctInterpretationValue)
        self.colorsNumberLabel = QtGui.QLabel(self.colorTableTab)
        self.colorsNumberLabel.setText(QtGui.QApplication.translate("bandDialog", "Number of entries:", None, QtGui.QApplication.UnicodeUTF8))
        self.colorsNumberLabel.setObjectName(_fromUtf8("colorsNumberLabel"))
        self.colorFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.colorsNumberLabel)
        self.colorsNumberValue = QtGui.QLabel(self.colorTableTab)
        self.colorsNumberValue.setText(QtGui.QApplication.translate("bandDialog", "number of entries value", None, QtGui.QApplication.UnicodeUTF8))
        self.colorsNumberValue.setObjectName(_fromUtf8("colorsNumberValue"))
        self.colorFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.colorsNumberValue)
        self.colorHorizontalLayout.addLayout(self.colorFormLayout)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.colorHorizontalLayout.addItem(spacerItem8)
        self.colorTabVerticalLayout.addLayout(self.colorHorizontalLayout)
        self.colorTableWidget = QtGui.QTableWidget(self.colorTableTab)
        self.colorTableWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.colorTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.colorTableWidget.setObjectName(_fromUtf8("colorTableWidget"))
        self.colorTableWidget.setColumnCount(4)
        self.colorTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("bandDialog", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.colorTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("bandDialog", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.colorTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("bandDialog", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.colorTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("bandDialog", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.colorTableWidget.setHorizontalHeaderItem(3, item)
        self.colorTableWidget.horizontalHeader().setStretchLastSection(True)
        self.colorTabVerticalLayout.addWidget(self.colorTableWidget)
        self.tabWidget.addTab(self.colorTableTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(bandDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.actionCopy = QtGui.QAction(bandDialog)
        self.actionCopy.setText(QtGui.QApplication.translate("bandDialog", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setToolTip(QtGui.QApplication.translate("bandDialog", "Copy to clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("bandDialog", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionSelectAll = QtGui.QAction(bandDialog)
        self.actionSelectAll.setText(QtGui.QApplication.translate("bandDialog", "Select &All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setToolTip(QtGui.QApplication.translate("bandDialog", "Select all items", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setObjectName(_fromUtf8("actionSelectAll"))

        self.retranslateUi(bandDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), bandDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), bandDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(bandDialog)

    def retranslateUi(self, bandDialog):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), QtGui.QApplication.translate("bandDialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.metadataTab), QtGui.QApplication.translate("bandDialog", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        item = self.histogramTableWidget.horizontalHeaderItem(0)
        item = self.histogramTableWidget.horizontalHeaderItem(1)
        item = self.histogramTableWidget.horizontalHeaderItem(2)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statisticsTab), QtGui.QApplication.translate("bandDialog", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        item = self.colorTableWidget.horizontalHeaderItem(0)
        item = self.colorTableWidget.horizontalHeaderItem(1)
        item = self.colorTableWidget.horizontalHeaderItem(2)
        item = self.colorTableWidget.horizontalHeaderItem(3)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.colorTableTab), QtGui.QApplication.translate("bandDialog", "Color Table", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    bandDialog = QtGui.QDialog()
    ui = Ui_bandDialog()
    ui.setupUi(bandDialog)
    bandDialog.show()
    sys.exit(app.exec_())

