# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gsdview/gdalbackend/ui/datasetdialog.ui'
#
# Created: Sun Nov 13 21:17:58 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_datasetDialog(object):
    def setupUi(self, datasetDialog):
        datasetDialog.setObjectName(_fromUtf8("datasetDialog"))
        datasetDialog.resize(472, 531)
        datasetDialog.setWindowTitle(QtGui.QApplication.translate("datasetDialog", "GDAL Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.mainVerticalLayout = QtGui.QVBoxLayout(datasetDialog)
        self.mainVerticalLayout.setObjectName(_fromUtf8("mainVerticalLayout"))
        self.tabWidget = QtGui.QTabWidget(datasetDialog)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.infoTab = QtGui.QWidget()
        self.infoTab.setObjectName(_fromUtf8("infoTab"))
        self.infoTabVerticalLayout = QtGui.QVBoxLayout(self.infoTab)
        self.infoTabVerticalLayout.setObjectName(_fromUtf8("infoTabVerticalLayout"))
        self.infoGroupBox = QtGui.QGroupBox(self.infoTab)
        self.infoGroupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.infoGroupBox.setObjectName(_fromUtf8("infoGroupBox"))
        self.infoFormLayout = QtGui.QFormLayout(self.infoGroupBox)
        self.infoFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.infoFormLayout.setObjectName(_fromUtf8("infoFormLayout"))
        self.descriptionLabel = QtGui.QLabel(self.infoGroupBox)
        self.descriptionLabel.setText(QtGui.QApplication.translate("datasetDialog", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.infoFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.descriptionLabel)
        self.rasterCountLabel = QtGui.QLabel(self.infoGroupBox)
        self.rasterCountLabel.setText(QtGui.QApplication.translate("datasetDialog", "Raster count:", None, QtGui.QApplication.UnicodeUTF8))
        self.rasterCountLabel.setObjectName(_fromUtf8("rasterCountLabel"))
        self.infoFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.rasterCountLabel)
        self.rasterCountValue = QtGui.QLabel(self.infoGroupBox)
        self.rasterCountValue.setText(QtGui.QApplication.translate("datasetDialog", "raster count value", None, QtGui.QApplication.UnicodeUTF8))
        self.rasterCountValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.rasterCountValue.setObjectName(_fromUtf8("rasterCountValue"))
        self.infoFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.rasterCountValue)
        self.descriptionValue = QtGui.QLineEdit(self.infoGroupBox)
        self.descriptionValue.setReadOnly(True)
        self.descriptionValue.setObjectName(_fromUtf8("descriptionValue"))
        self.infoFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.descriptionValue)
        self.infoTabVerticalLayout.addWidget(self.infoGroupBox)
        self.imageHorizontalLayout = QtGui.QHBoxLayout()
        self.imageHorizontalLayout.setObjectName(_fromUtf8("imageHorizontalLayout"))
        self.rasterGroupBox = QtGui.QGroupBox(self.infoTab)
        self.rasterGroupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.rasterGroupBox.setCheckable(False)
        self.rasterGroupBox.setObjectName(_fromUtf8("rasterGroupBox"))
        self.rasterFormLayout = QtGui.QFormLayout(self.rasterGroupBox)
        self.rasterFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.rasterFormLayout.setObjectName(_fromUtf8("rasterFormLayout"))
        self.xSizeLabel = QtGui.QLabel(self.rasterGroupBox)
        self.xSizeLabel.setText(QtGui.QApplication.translate("datasetDialog", "X Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.xSizeLabel.setObjectName(_fromUtf8("xSizeLabel"))
        self.rasterFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.xSizeLabel)
        self.xSizeValue = QtGui.QLabel(self.rasterGroupBox)
        self.xSizeValue.setText(QtGui.QApplication.translate("datasetDialog", "x size value", None, QtGui.QApplication.UnicodeUTF8))
        self.xSizeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.xSizeValue.setObjectName(_fromUtf8("xSizeValue"))
        self.rasterFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.xSizeValue)
        self.ySizeLabel = QtGui.QLabel(self.rasterGroupBox)
        self.ySizeLabel.setText(QtGui.QApplication.translate("datasetDialog", "Y Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.ySizeLabel.setObjectName(_fromUtf8("ySizeLabel"))
        self.rasterFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ySizeLabel)
        self.ySizeValue = QtGui.QLabel(self.rasterGroupBox)
        self.ySizeValue.setText(QtGui.QApplication.translate("datasetDialog", "y size value", None, QtGui.QApplication.UnicodeUTF8))
        self.ySizeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ySizeValue.setObjectName(_fromUtf8("ySizeValue"))
        self.rasterFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ySizeValue)
        self.imageHorizontalLayout.addWidget(self.rasterGroupBox)
        self.imageStructureGroupBox = QtGui.QGroupBox(self.infoTab)
        self.imageStructureGroupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "Image Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.imageStructureGroupBox.setObjectName(_fromUtf8("imageStructureGroupBox"))
        self.imageStructureFormLayout = QtGui.QFormLayout(self.imageStructureGroupBox)
        self.imageStructureFormLayout.setObjectName(_fromUtf8("imageStructureFormLayout"))
        self.compressionLabel = QtGui.QLabel(self.imageStructureGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compressionLabel.sizePolicy().hasHeightForWidth())
        self.compressionLabel.setSizePolicy(sizePolicy)
        self.compressionLabel.setText(QtGui.QApplication.translate("datasetDialog", "Compression:", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionLabel.setObjectName(_fromUtf8("compressionLabel"))
        self.imageStructureFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.compressionLabel)
        self.compressionValue = QtGui.QLabel(self.imageStructureGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compressionValue.sizePolicy().hasHeightForWidth())
        self.compressionValue.setSizePolicy(sizePolicy)
        self.compressionValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "The compression type used for this dataset or band.\n"
"\n"
"There is no fixed catalog of compression type names, but where a given\n"
"format includes a COMPRESSION creation option, the same list of values\n"
"should be used here as there.", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "The compression type used for this dataset or band.\n"
"\n"
"There is no fixed catalog of compression type names, but where a given\n"
"format includes a COMPRESSION creation option, the same list of values\n"
"should be used here as there.", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionValue.setText(QtGui.QApplication.translate("datasetDialog", "compression value", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.compressionValue.setObjectName(_fromUtf8("compressionValue"))
        self.imageStructureFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.compressionValue)
        self.nbitsLabel = QtGui.QLabel(self.imageStructureGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbitsLabel.sizePolicy().hasHeightForWidth())
        self.nbitsLabel.setSizePolicy(sizePolicy)
        self.nbitsLabel.setText(QtGui.QApplication.translate("datasetDialog", "Numbero of bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.nbitsLabel.setObjectName(_fromUtf8("nbitsLabel"))
        self.imageStructureFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.nbitsLabel)
        self.nbitsValue = QtGui.QLabel(self.imageStructureGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbitsValue.sizePolicy().hasHeightForWidth())
        self.nbitsValue.setSizePolicy(sizePolicy)
        self.nbitsValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "The actual number of bits used for this band, or the bands of this dataset.\n"
"\n"
"Normally only present when the number of bits is non-standard for the\n"
"datatype, such as when a 1 bit TIFF is represented through GDAL as GDT_Byte.", None, QtGui.QApplication.UnicodeUTF8))
        self.nbitsValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "The actual number of bits used for this band, or the bands of this dataset.\n"
"\n"
"Normally only present when the number of bits is non-standard for the\n"
"datatype, such as when a 1 bit TIFF is represented through GDAL as GDT_Byte.", None, QtGui.QApplication.UnicodeUTF8))
        self.nbitsValue.setText(QtGui.QApplication.translate("datasetDialog", "nbits value", None, QtGui.QApplication.UnicodeUTF8))
        self.nbitsValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.nbitsValue.setObjectName(_fromUtf8("nbitsValue"))
        self.imageStructureFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nbitsValue)
        self.interleaveLabel = QtGui.QLabel(self.imageStructureGroupBox)
        self.interleaveLabel.setText(QtGui.QApplication.translate("datasetDialog", "Interleave:", None, QtGui.QApplication.UnicodeUTF8))
        self.interleaveLabel.setObjectName(_fromUtf8("interleaveLabel"))
        self.imageStructureFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.interleaveLabel)
        self.interleaveValue = QtGui.QLabel(self.imageStructureGroupBox)
        self.interleaveValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "This only applies on datasets, and the value should be one\n"
"of PIXEL, LINE or BAND. It can be used as a data access hint.", None, QtGui.QApplication.UnicodeUTF8))
        self.interleaveValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "This only applies on datasets, and the value should be one\n"
"of PIXEL, LINE or BAND. It can be used as a data access hint.", None, QtGui.QApplication.UnicodeUTF8))
        self.interleaveValue.setText(QtGui.QApplication.translate("datasetDialog", "interleave value", None, QtGui.QApplication.UnicodeUTF8))
        self.interleaveValue.setObjectName(_fromUtf8("interleaveValue"))
        self.imageStructureFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.interleaveValue)
        self.pixelTypeLabel = QtGui.QLabel(self.imageStructureGroupBox)
        self.pixelTypeLabel.setText(QtGui.QApplication.translate("datasetDialog", "Pixel type:", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelTypeLabel.setObjectName(_fromUtf8("pixelTypeLabel"))
        self.imageStructureFormLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.pixelTypeLabel)
        self.pixelTypeValue = QtGui.QLabel(self.imageStructureGroupBox)
        self.pixelTypeValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "This may appear on a GDT_Byte band (or the corresponding dataset)\n"
"and have the value SIGNEDBYTE to indicate the unsigned byte values\n"
"between 128 and 255 should be interpreted as being values between -128\n"
"and -1 for applications that recognise the SIGNEDBYTE type.", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelTypeValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "This may appear on a GDT_Byte band (or the corresponding dataset)\n"
"and have the value SIGNEDBYTE to indicate the unsigned byte values\n"
"between 128 and 255 should be interpreted as being values between -128\n"
"and -1 for applications that recognise the SIGNEDBYTE type.", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelTypeValue.setText(QtGui.QApplication.translate("datasetDialog", "pixel type value", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelTypeValue.setObjectName(_fromUtf8("pixelTypeValue"))
        self.imageStructureFormLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pixelTypeValue)
        self.imageHorizontalLayout.addWidget(self.imageStructureGroupBox)
        self.infoTabVerticalLayout.addLayout(self.imageHorizontalLayout)
        self.transformGroupBox = QtGui.QGroupBox(self.infoTab)
        self.transformGroupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.transformGroupBox.setObjectName(_fromUtf8("transformGroupBox"))
        self.transformHorizontalLayout = QtGui.QHBoxLayout(self.transformGroupBox)
        self.transformHorizontalLayout.setObjectName(_fromUtf8("transformHorizontalLayout"))
        self.transformGridLayout = QtGui.QGridLayout()
        self.transformGridLayout.setObjectName(_fromUtf8("transformGridLayout"))
        self.xLabel = QtGui.QLabel(self.transformGroupBox)
        self.xLabel.setText(QtGui.QApplication.translate("datasetDialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel.setObjectName(_fromUtf8("xLabel"))
        self.transformGridLayout.addWidget(self.xLabel, 0, 0, 1, 1)
        self.eqLabel1 = QtGui.QLabel(self.transformGroupBox)
        self.eqLabel1.setText(QtGui.QApplication.translate("datasetDialog", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.eqLabel1.setObjectName(_fromUtf8("eqLabel1"))
        self.transformGridLayout.addWidget(self.eqLabel1, 0, 1, 1, 1)
        self.xOffsetValue = QtGui.QLabel(self.transformGroupBox)
        self.xOffsetValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "X offset", None, QtGui.QApplication.UnicodeUTF8))
        self.xOffsetValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "X offset", None, QtGui.QApplication.UnicodeUTF8))
        self.xOffsetValue.setText(QtGui.QApplication.translate("datasetDialog", "xoffset", None, QtGui.QApplication.UnicodeUTF8))
        self.xOffsetValue.setObjectName(_fromUtf8("xOffsetValue"))
        self.transformGridLayout.addWidget(self.xOffsetValue, 0, 2, 1, 1)
        self.plus11Label = QtGui.QLabel(self.transformGroupBox)
        self.plus11Label.setText(QtGui.QApplication.translate("datasetDialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.plus11Label.setObjectName(_fromUtf8("plus11Label"))
        self.transformGridLayout.addWidget(self.plus11Label, 0, 3, 1, 1)
        self.a11Value = QtGui.QLabel(self.transformGroupBox)
        self.a11Value.setToolTip(QtGui.QApplication.translate("datasetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">A</span><span style=\" font-size:12pt; vertical-align:sub;\">11</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.a11Value.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">A</span><span style=\" font-size:12pt; vertical-align:sub;\">11</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.a11Value.setText(QtGui.QApplication.translate("datasetDialog", "a11", None, QtGui.QApplication.UnicodeUTF8))
        self.a11Value.setObjectName(_fromUtf8("a11Value"))
        self.transformGridLayout.addWidget(self.a11Value, 0, 4, 1, 1)
        self.mul11Label = QtGui.QLabel(self.transformGroupBox)
        self.mul11Label.setText(QtGui.QApplication.translate("datasetDialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.mul11Label.setObjectName(_fromUtf8("mul11Label"))
        self.transformGridLayout.addWidget(self.mul11Label, 0, 5, 1, 1)
        self.pix1Value = QtGui.QLabel(self.transformGroupBox)
        self.pix1Value.setText(QtGui.QApplication.translate("datasetDialog", "pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.pix1Value.setObjectName(_fromUtf8("pix1Value"))
        self.transformGridLayout.addWidget(self.pix1Value, 0, 6, 1, 1)
        self.plus12Label = QtGui.QLabel(self.transformGroupBox)
        self.plus12Label.setText(QtGui.QApplication.translate("datasetDialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.plus12Label.setObjectName(_fromUtf8("plus12Label"))
        self.transformGridLayout.addWidget(self.plus12Label, 0, 7, 1, 1)
        self.a12Value = QtGui.QLabel(self.transformGroupBox)
        self.a12Value.setToolTip(QtGui.QApplication.translate("datasetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">A</span><span style=\" font-size:12pt; vertical-align:sub;\">12</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.a12Value.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">A</span><span style=\" font-size:12pt; vertical-align:sub;\">12</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.a12Value.setText(QtGui.QApplication.translate("datasetDialog", "a12", None, QtGui.QApplication.UnicodeUTF8))
        self.a12Value.setObjectName(_fromUtf8("a12Value"))
        self.transformGridLayout.addWidget(self.a12Value, 0, 8, 1, 1)
        self.mul12Label = QtGui.QLabel(self.transformGroupBox)
        self.mul12Label.setText(QtGui.QApplication.translate("datasetDialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.mul12Label.setObjectName(_fromUtf8("mul12Label"))
        self.transformGridLayout.addWidget(self.mul12Label, 0, 9, 1, 1)
        self.line1Value = QtGui.QLabel(self.transformGroupBox)
        self.line1Value.setText(QtGui.QApplication.translate("datasetDialog", "line", None, QtGui.QApplication.UnicodeUTF8))
        self.line1Value.setObjectName(_fromUtf8("line1Value"))
        self.transformGridLayout.addWidget(self.line1Value, 0, 10, 1, 1)
        self.yLabel = QtGui.QLabel(self.transformGroupBox)
        self.yLabel.setText(QtGui.QApplication.translate("datasetDialog", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.yLabel.setObjectName(_fromUtf8("yLabel"))
        self.transformGridLayout.addWidget(self.yLabel, 1, 0, 1, 1)
        self.eqLabel2 = QtGui.QLabel(self.transformGroupBox)
        self.eqLabel2.setText(QtGui.QApplication.translate("datasetDialog", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.eqLabel2.setObjectName(_fromUtf8("eqLabel2"))
        self.transformGridLayout.addWidget(self.eqLabel2, 1, 1, 1, 2)
        self.yOffsetValue = QtGui.QLabel(self.transformGroupBox)
        self.yOffsetValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "Y offset", None, QtGui.QApplication.UnicodeUTF8))
        self.yOffsetValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "Y offset", None, QtGui.QApplication.UnicodeUTF8))
        self.yOffsetValue.setText(QtGui.QApplication.translate("datasetDialog", "yoffset", None, QtGui.QApplication.UnicodeUTF8))
        self.yOffsetValue.setObjectName(_fromUtf8("yOffsetValue"))
        self.transformGridLayout.addWidget(self.yOffsetValue, 1, 2, 1, 1)
        self.plus21Label = QtGui.QLabel(self.transformGroupBox)
        self.plus21Label.setText(QtGui.QApplication.translate("datasetDialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.plus21Label.setObjectName(_fromUtf8("plus21Label"))
        self.transformGridLayout.addWidget(self.plus21Label, 1, 3, 1, 1)
        self.a21Value = QtGui.QLabel(self.transformGroupBox)
        self.a21Value.setToolTip(QtGui.QApplication.translate("datasetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">A</span><span style=\" font-size:12pt; vertical-align:sub;\">21</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.a21Value.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">A</span><span style=\" font-size:12pt; vertical-align:sub;\">21</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.a21Value.setText(QtGui.QApplication.translate("datasetDialog", "a21", None, QtGui.QApplication.UnicodeUTF8))
        self.a21Value.setObjectName(_fromUtf8("a21Value"))
        self.transformGridLayout.addWidget(self.a21Value, 1, 4, 1, 1)
        self.mul21Label = QtGui.QLabel(self.transformGroupBox)
        self.mul21Label.setText(QtGui.QApplication.translate("datasetDialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.mul21Label.setObjectName(_fromUtf8("mul21Label"))
        self.transformGridLayout.addWidget(self.mul21Label, 1, 5, 1, 1)
        self.pix2Value = QtGui.QLabel(self.transformGroupBox)
        self.pix2Value.setText(QtGui.QApplication.translate("datasetDialog", "pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.pix2Value.setObjectName(_fromUtf8("pix2Value"))
        self.transformGridLayout.addWidget(self.pix2Value, 1, 6, 1, 1)
        self.plus22Label = QtGui.QLabel(self.transformGroupBox)
        self.plus22Label.setText(QtGui.QApplication.translate("datasetDialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.plus22Label.setObjectName(_fromUtf8("plus22Label"))
        self.transformGridLayout.addWidget(self.plus22Label, 1, 7, 1, 1)
        self.a22Value = QtGui.QLabel(self.transformGroupBox)
        self.a22Value.setToolTip(QtGui.QApplication.translate("datasetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">A</span><span style=\" font-size:12pt; vertical-align:sub;\">22</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.a22Value.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">A</span><span style=\" font-size:12pt; vertical-align:sub;\">22</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.a22Value.setText(QtGui.QApplication.translate("datasetDialog", "a22", None, QtGui.QApplication.UnicodeUTF8))
        self.a22Value.setObjectName(_fromUtf8("a22Value"))
        self.transformGridLayout.addWidget(self.a22Value, 1, 8, 1, 1)
        self.mul22Label = QtGui.QLabel(self.transformGroupBox)
        self.mul22Label.setText(QtGui.QApplication.translate("datasetDialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.mul22Label.setObjectName(_fromUtf8("mul22Label"))
        self.transformGridLayout.addWidget(self.mul22Label, 1, 9, 1, 1)
        self.line2Value = QtGui.QLabel(self.transformGroupBox)
        self.line2Value.setText(QtGui.QApplication.translate("datasetDialog", "line", None, QtGui.QApplication.UnicodeUTF8))
        self.line2Value.setObjectName(_fromUtf8("line2Value"))
        self.transformGridLayout.addWidget(self.line2Value, 1, 10, 1, 1)
        self.transformHorizontalLayout.addLayout(self.transformGridLayout)
        spacerItem = QtGui.QSpacerItem(53, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.transformHorizontalLayout.addItem(spacerItem)
        self.infoTabVerticalLayout.addWidget(self.transformGroupBox)
        self.projectionHorizontalLayout = QtGui.QHBoxLayout()
        self.projectionHorizontalLayout.setObjectName(_fromUtf8("projectionHorizontalLayout"))
        self.projectionGroupBox = QtGui.QGroupBox(self.infoTab)
        self.projectionGroupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "Projection", None, QtGui.QApplication.UnicodeUTF8))
        self.projectionGroupBox.setCheckable(False)
        self.projectionGroupBox.setObjectName(_fromUtf8("projectionGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.projectionGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.projectionValue = QtGui.QTextBrowser(self.projectionGroupBox)
        self.projectionValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "The projection reference string for this dataset in OGC WKT or PROJ.4 format.", None, QtGui.QApplication.UnicodeUTF8))
        self.projectionValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "The projection reference string for this dataset in OGC WKT or PROJ.4 format.", None, QtGui.QApplication.UnicodeUTF8))
        self.projectionValue.setObjectName(_fromUtf8("projectionValue"))
        self.verticalLayout_2.addWidget(self.projectionValue)
        self.projectionHorizontalLayout.addWidget(self.projectionGroupBox)
        self.projectionRefGroupBox = QtGui.QGroupBox(self.infoTab)
        self.projectionRefGroupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "ProjectionRef", None, QtGui.QApplication.UnicodeUTF8))
        self.projectionRefGroupBox.setObjectName(_fromUtf8("projectionRefGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.projectionRefGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.projectionRefValue = QtGui.QTextBrowser(self.projectionRefGroupBox)
        self.projectionRefValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "The projection definition string for this dataset.", None, QtGui.QApplication.UnicodeUTF8))
        self.projectionRefValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "The projection definition string for this dataset.\n"
"\n"
"The returned string defines the projection coordinate system of the image in\n"
"OpenGIS WKT format.", None, QtGui.QApplication.UnicodeUTF8))
        self.projectionRefValue.setObjectName(_fromUtf8("projectionRefValue"))
        self.verticalLayout_3.addWidget(self.projectionRefValue)
        self.projectionHorizontalLayout.addWidget(self.projectionRefGroupBox)
        self.infoTabVerticalLayout.addLayout(self.projectionHorizontalLayout)
        self.tabWidget.addTab(self.infoTab, _fromUtf8(""))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.infoTab), QtGui.QApplication.translate("datasetDialog", "General information about the dataset.", None, QtGui.QApplication.UnicodeUTF8))
        self.metadataTab = QtGui.QWidget()
        self.metadataTab.setObjectName(_fromUtf8("metadataTab"))
        self.metadataTabVerticalLayout = QtGui.QVBoxLayout(self.metadataTab)
        self.metadataTabVerticalLayout.setSpacing(0)
        self.metadataTabVerticalLayout.setMargin(0)
        self.metadataTabVerticalLayout.setObjectName(_fromUtf8("metadataTabVerticalLayout"))
        self.tabWidget.addTab(self.metadataTab, _fromUtf8(""))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.metadataTab), QtGui.QApplication.translate("datasetDialog", "Dataset metadata.", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsTab = QtGui.QWidget()
        self.gcpsTab.setObjectName(_fromUtf8("gcpsTab"))
        self.gcpsTabVerticalLayout = QtGui.QVBoxLayout(self.gcpsTab)
        self.gcpsTabVerticalLayout.setObjectName(_fromUtf8("gcpsTabVerticalLayout"))
        self.gcpsProjectionGroupBox = QtGui.QGroupBox(self.gcpsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gcpsProjectionGroupBox.sizePolicy().hasHeightForWidth())
        self.gcpsProjectionGroupBox.setSizePolicy(sizePolicy)
        self.gcpsProjectionGroupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.gcpsProjectionGroupBox.setMaximumSize(QtCore.QSize(16777215, 180))
        self.gcpsProjectionGroupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.gcpsProjectionGroupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "GCPs Projection", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsProjectionGroupBox.setObjectName(_fromUtf8("gcpsProjectionGroupBox"))
        self.gcpsProjectionVerticalLayout = QtGui.QVBoxLayout(self.gcpsProjectionGroupBox)
        self.gcpsProjectionVerticalLayout.setObjectName(_fromUtf8("gcpsProjectionVerticalLayout"))
        self.gcpsProjectionValue = QtGui.QTextEdit(self.gcpsProjectionGroupBox)
        self.gcpsProjectionValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "The projection definition string for this dataset.\n"
"\n"
"The returned string defines the projection coordinate system of the image in\n"
"OpenGIS WKT format.", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsProjectionValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "The projection definition string for this dataset.\n"
"\n"
"The returned string defines the projection coordinate system of the image in\n"
"OpenGIS WKT format.", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsProjectionValue.setReadOnly(True)
        self.gcpsProjectionValue.setObjectName(_fromUtf8("gcpsProjectionValue"))
        self.gcpsProjectionVerticalLayout.addWidget(self.gcpsProjectionValue)
        self.gcpsTabVerticalLayout.addWidget(self.gcpsProjectionGroupBox)
        self.gcpsGoupBox = QtGui.QGroupBox(self.gcpsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.gcpsGoupBox.sizePolicy().hasHeightForWidth())
        self.gcpsGoupBox.setSizePolicy(sizePolicy)
        self.gcpsGoupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.gcpsGoupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gcpsGoupBox.setSizeIncrement(QtCore.QSize(0, 2))
        self.gcpsGoupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "GCPs", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsGoupBox.setObjectName(_fromUtf8("gcpsGoupBox"))
        self.gcpsVerticalLayout = QtGui.QVBoxLayout(self.gcpsGoupBox)
        self.gcpsVerticalLayout.setObjectName(_fromUtf8("gcpsVerticalLayout"))
        self.gcpsNumHorizontalLayout = QtGui.QHBoxLayout()
        self.gcpsNumHorizontalLayout.setObjectName(_fromUtf8("gcpsNumHorizontalLayout"))
        self.gcpsNumLabel = QtGui.QLabel(self.gcpsGoupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gcpsNumLabel.sizePolicy().hasHeightForWidth())
        self.gcpsNumLabel.setSizePolicy(sizePolicy)
        self.gcpsNumLabel.setText(QtGui.QApplication.translate("datasetDialog", "Number of metadata:", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsNumLabel.setObjectName(_fromUtf8("gcpsNumLabel"))
        self.gcpsNumHorizontalLayout.addWidget(self.gcpsNumLabel)
        self.gcpsNumValue = QtGui.QLabel(self.gcpsGoupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gcpsNumValue.sizePolicy().hasHeightForWidth())
        self.gcpsNumValue.setSizePolicy(sizePolicy)
        self.gcpsNumValue.setSizeIncrement(QtCore.QSize(1, 0))
        self.gcpsNumValue.setText(QtGui.QApplication.translate("datasetDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsNumValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.gcpsNumValue.setObjectName(_fromUtf8("gcpsNumValue"))
        self.gcpsNumHorizontalLayout.addWidget(self.gcpsNumValue)
        self.gcpsVerticalLayout.addLayout(self.gcpsNumHorizontalLayout)
        self.gcpsTableWidget = QtGui.QTableWidget(self.gcpsGoupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.gcpsTableWidget.sizePolicy().hasHeightForWidth())
        self.gcpsTableWidget.setSizePolicy(sizePolicy)
        self.gcpsTableWidget.setSizeIncrement(QtCore.QSize(0, 10))
        self.gcpsTableWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.gcpsTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.gcpsTableWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.gcpsTableWidget.setObjectName(_fromUtf8("gcpsTableWidget"))
        self.gcpsTableWidget.setColumnCount(6)
        self.gcpsTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("datasetDialog", "Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("datasetDialog", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("datasetDialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("datasetDialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("datasetDialog", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("datasetDialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.gcpsTableWidget.setHorizontalHeaderItem(5, item)
        self.gcpsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.gcpsVerticalLayout.addWidget(self.gcpsTableWidget)
        self.gcpsTabVerticalLayout.addWidget(self.gcpsGoupBox)
        self.tabWidget.addTab(self.gcpsTab, _fromUtf8(""))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.gcpsTab), QtGui.QApplication.translate("datasetDialog", "Ground Control Points (GCPs).", None, QtGui.QApplication.UnicodeUTF8))
        self.driverTab = QtGui.QWidget()
        self.driverTab.setObjectName(_fromUtf8("driverTab"))
        self.driverTabVerticalLayout = QtGui.QVBoxLayout(self.driverTab)
        self.driverTabVerticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.driverTabVerticalLayout.setObjectName(_fromUtf8("driverTabVerticalLayout"))
        self.driverGroupBox = QtGui.QGroupBox(self.driverTab)
        self.driverGroupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "Driver Info", None, QtGui.QApplication.UnicodeUTF8))
        self.driverGroupBox.setObjectName(_fromUtf8("driverGroupBox"))
        self.driverHorizontalLayout = QtGui.QHBoxLayout(self.driverGroupBox)
        self.driverHorizontalLayout.setObjectName(_fromUtf8("driverHorizontalLayout"))
        self.driverGridLayout = QtGui.QGridLayout()
        self.driverGridLayout.setObjectName(_fromUtf8("driverGridLayout"))
        self.driverShortNameLabel = QtGui.QLabel(self.driverGroupBox)
        self.driverShortNameLabel.setText(QtGui.QApplication.translate("datasetDialog", "Short Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.driverShortNameLabel.setObjectName(_fromUtf8("driverShortNameLabel"))
        self.driverGridLayout.addWidget(self.driverShortNameLabel, 0, 0, 1, 1)
        self.driverShortNameValue = QtGui.QLabel(self.driverGroupBox)
        self.driverShortNameValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "Short name of the driver.", None, QtGui.QApplication.UnicodeUTF8))
        self.driverShortNameValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "Short name of the driver.", None, QtGui.QApplication.UnicodeUTF8))
        self.driverShortNameValue.setText(QtGui.QApplication.translate("datasetDialog", "short name", None, QtGui.QApplication.UnicodeUTF8))
        self.driverShortNameValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.driverShortNameValue.setObjectName(_fromUtf8("driverShortNameValue"))
        self.driverGridLayout.addWidget(self.driverShortNameValue, 0, 1, 1, 1)
        self.driverLongNameLabel = QtGui.QLabel(self.driverGroupBox)
        self.driverLongNameLabel.setText(QtGui.QApplication.translate("datasetDialog", "Long Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.driverLongNameLabel.setObjectName(_fromUtf8("driverLongNameLabel"))
        self.driverGridLayout.addWidget(self.driverLongNameLabel, 1, 0, 1, 1)
        self.driverLongNameValue = QtGui.QLabel(self.driverGroupBox)
        self.driverLongNameValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "Long name of the driver.", None, QtGui.QApplication.UnicodeUTF8))
        self.driverLongNameValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "Long name of the driver.", None, QtGui.QApplication.UnicodeUTF8))
        self.driverLongNameValue.setText(QtGui.QApplication.translate("datasetDialog", "long name", None, QtGui.QApplication.UnicodeUTF8))
        self.driverLongNameValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.driverLongNameValue.setObjectName(_fromUtf8("driverLongNameValue"))
        self.driverGridLayout.addWidget(self.driverLongNameValue, 1, 1, 1, 1)
        self.driverDescriptionLabel = QtGui.QLabel(self.driverGroupBox)
        self.driverDescriptionLabel.setText(QtGui.QApplication.translate("datasetDialog", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.driverDescriptionLabel.setObjectName(_fromUtf8("driverDescriptionLabel"))
        self.driverGridLayout.addWidget(self.driverDescriptionLabel, 2, 0, 1, 1)
        self.driverDescriptionValue = QtGui.QLabel(self.driverGroupBox)
        self.driverDescriptionValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "Driver description.", None, QtGui.QApplication.UnicodeUTF8))
        self.driverDescriptionValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "Driver description.", None, QtGui.QApplication.UnicodeUTF8))
        self.driverDescriptionValue.setText(QtGui.QApplication.translate("datasetDialog", "description text", None, QtGui.QApplication.UnicodeUTF8))
        self.driverDescriptionValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.driverDescriptionValue.setObjectName(_fromUtf8("driverDescriptionValue"))
        self.driverGridLayout.addWidget(self.driverDescriptionValue, 2, 1, 1, 1)
        self.driverHelpTopicLabel = QtGui.QLabel(self.driverGroupBox)
        self.driverHelpTopicLabel.setText(QtGui.QApplication.translate("datasetDialog", "Help topic:", None, QtGui.QApplication.UnicodeUTF8))
        self.driverHelpTopicLabel.setObjectName(_fromUtf8("driverHelpTopicLabel"))
        self.driverGridLayout.addWidget(self.driverHelpTopicLabel, 3, 0, 1, 1)
        self.driverHelpTopicValue = QtGui.QLabel(self.driverGroupBox)
        self.driverHelpTopicValue.setToolTip(QtGui.QApplication.translate("datasetDialog", "Help topic in the GDAL library documentation.", None, QtGui.QApplication.UnicodeUTF8))
        self.driverHelpTopicValue.setWhatsThis(QtGui.QApplication.translate("datasetDialog", "Help topic in the GDAL library documentation.", None, QtGui.QApplication.UnicodeUTF8))
        self.driverHelpTopicValue.setText(QtGui.QApplication.translate("datasetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.gdal.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">help topic</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.driverHelpTopicValue.setOpenExternalLinks(True)
        self.driverHelpTopicValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.driverHelpTopicValue.setObjectName(_fromUtf8("driverHelpTopicValue"))
        self.driverGridLayout.addWidget(self.driverHelpTopicValue, 3, 1, 1, 1)
        self.driverHorizontalLayout.addLayout(self.driverGridLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.driverHorizontalLayout.addItem(spacerItem1)
        self.driverTabVerticalLayout.addWidget(self.driverGroupBox)
        self.driverMetadataGroupBox = QtGui.QGroupBox(self.driverTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.driverMetadataGroupBox.sizePolicy().hasHeightForWidth())
        self.driverMetadataGroupBox.setSizePolicy(sizePolicy)
        self.driverMetadataGroupBox.setTitle(QtGui.QApplication.translate("datasetDialog", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.driverMetadataGroupBox.setObjectName(_fromUtf8("driverMetadataGroupBox"))
        self.driverMetadataVerticalLayout = QtGui.QVBoxLayout(self.driverMetadataGroupBox)
        self.driverMetadataVerticalLayout.setSpacing(0)
        self.driverMetadataVerticalLayout.setMargin(0)
        self.driverMetadataVerticalLayout.setObjectName(_fromUtf8("driverMetadataVerticalLayout"))
        self.driverTabVerticalLayout.addWidget(self.driverMetadataGroupBox)
        self.tabWidget.addTab(self.driverTab, _fromUtf8(""))
        self.filesTab = QtGui.QWidget()
        self.filesTab.setObjectName(_fromUtf8("filesTab"))
        self.filesTabVerticalLayout = QtGui.QVBoxLayout(self.filesTab)
        self.filesTabVerticalLayout.setObjectName(_fromUtf8("filesTabVerticalLayout"))
        self.fileListWidget = QtGui.QListWidget(self.filesTab)
        self.fileListWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.fileListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fileListWidget.setObjectName(_fromUtf8("fileListWidget"))
        self.filesTabVerticalLayout.addWidget(self.fileListWidget)
        self.tabWidget.addTab(self.filesTab, _fromUtf8(""))
        self.mainVerticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(datasetDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.mainVerticalLayout.addWidget(self.buttonBox)
        self.actionCopy = QtGui.QAction(datasetDialog)
        self.actionCopy.setText(QtGui.QApplication.translate("datasetDialog", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setToolTip(QtGui.QApplication.translate("datasetDialog", "Copy to clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("datasetDialog", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionSelectAll = QtGui.QAction(datasetDialog)
        self.actionSelectAll.setText(QtGui.QApplication.translate("datasetDialog", "Select &All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setToolTip(QtGui.QApplication.translate("datasetDialog", "Select all items", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setObjectName(_fromUtf8("actionSelectAll"))

        self.retranslateUi(datasetDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), datasetDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), datasetDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(datasetDialog)

    def retranslateUi(self, datasetDialog):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), QtGui.QApplication.translate("datasetDialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.metadataTab), QtGui.QApplication.translate("datasetDialog", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        item = self.gcpsTableWidget.horizontalHeaderItem(0)
        item = self.gcpsTableWidget.horizontalHeaderItem(1)
        item = self.gcpsTableWidget.horizontalHeaderItem(2)
        item = self.gcpsTableWidget.horizontalHeaderItem(3)
        item = self.gcpsTableWidget.horizontalHeaderItem(4)
        item = self.gcpsTableWidget.horizontalHeaderItem(5)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gcpsTab), QtGui.QApplication.translate("datasetDialog", "GCPs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.driverTab), QtGui.QApplication.translate("datasetDialog", "Driver", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filesTab), QtGui.QApplication.translate("datasetDialog", "Files", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    datasetDialog = QtGui.QDialog()
    ui = Ui_datasetDialog()
    ui.setupUi(datasetDialog)
    datasetDialog.show()
    sys.exit(app.exec_())

