# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gsdview/gdalbackend/ui/gdalinfo.ui'
#
# Created: Sun Nov 13 21:17:58 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_gdalInfoWidget(object):
    def setupUi(self, gdalInfoWidget):
        gdalInfoWidget.setObjectName(_fromUtf8("gdalInfoWidget"))
        gdalInfoWidget.resize(521, 421)
        gdalInfoWidget.setWindowTitle(QtGui.QApplication.translate("gdalInfoWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(gdalInfoWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gdalHorizontalLayout = QtGui.QHBoxLayout()
        self.gdalHorizontalLayout.setObjectName(_fromUtf8("gdalHorizontalLayout"))
        self.gdalVersionGroupBox = QtGui.QGroupBox(gdalInfoWidget)
        self.gdalVersionGroupBox.setTitle(QtGui.QApplication.translate("gdalInfoWidget", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalVersionGroupBox.setObjectName(_fromUtf8("gdalVersionGroupBox"))
        self.versionGridLayout = QtGui.QGridLayout(self.gdalVersionGroupBox)
        self.versionGridLayout.setObjectName(_fromUtf8("versionGridLayout"))
        self.gdalReleaseNameLabel = QtGui.QLabel(self.gdalVersionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalReleaseNameLabel.sizePolicy().hasHeightForWidth())
        self.gdalReleaseNameLabel.setSizePolicy(sizePolicy)
        self.gdalReleaseNameLabel.setText(QtGui.QApplication.translate("gdalInfoWidget", "Release Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalReleaseNameLabel.setObjectName(_fromUtf8("gdalReleaseNameLabel"))
        self.versionGridLayout.addWidget(self.gdalReleaseNameLabel, 0, 0, 1, 1)
        self.gdalReleaseNameValue = QtGui.QLabel(self.gdalVersionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalReleaseNameValue.sizePolicy().hasHeightForWidth())
        self.gdalReleaseNameValue.setSizePolicy(sizePolicy)
        self.gdalReleaseNameValue.setSizeIncrement(QtCore.QSize(1, 0))
        self.gdalReleaseNameValue.setText(QtGui.QApplication.translate("gdalInfoWidget", "1.5.4", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalReleaseNameValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.gdalReleaseNameValue.setObjectName(_fromUtf8("gdalReleaseNameValue"))
        self.versionGridLayout.addWidget(self.gdalReleaseNameValue, 0, 1, 1, 1)
        self.gdalReleaseDateLabel = QtGui.QLabel(self.gdalVersionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalReleaseDateLabel.sizePolicy().hasHeightForWidth())
        self.gdalReleaseDateLabel.setSizePolicy(sizePolicy)
        self.gdalReleaseDateLabel.setText(QtGui.QApplication.translate("gdalInfoWidget", "Relaease Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalReleaseDateLabel.setObjectName(_fromUtf8("gdalReleaseDateLabel"))
        self.versionGridLayout.addWidget(self.gdalReleaseDateLabel, 1, 0, 1, 1)
        self.gdalReleaseDateValue = QtGui.QLabel(self.gdalVersionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalReleaseDateValue.sizePolicy().hasHeightForWidth())
        self.gdalReleaseDateValue.setSizePolicy(sizePolicy)
        self.gdalReleaseDateValue.setSizeIncrement(QtCore.QSize(1, 0))
        self.gdalReleaseDateValue.setText(QtGui.QApplication.translate("gdalInfoWidget", "DD/MM/AAAA", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalReleaseDateValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.gdalReleaseDateValue.setObjectName(_fromUtf8("gdalReleaseDateValue"))
        self.versionGridLayout.addWidget(self.gdalReleaseDateValue, 1, 1, 1, 1)
        self.gdalHorizontalLayout.addWidget(self.gdalVersionGroupBox)
        self.gdalCacheGroupBox = QtGui.QGroupBox(gdalInfoWidget)
        self.gdalCacheGroupBox.setTitle(QtGui.QApplication.translate("gdalInfoWidget", "Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalCacheGroupBox.setObjectName(_fromUtf8("gdalCacheGroupBox"))
        self.cacheGridLayout = QtGui.QGridLayout(self.gdalCacheGroupBox)
        self.cacheGridLayout.setObjectName(_fromUtf8("cacheGridLayout"))
        self.gdalCacheMaxLabel = QtGui.QLabel(self.gdalCacheGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalCacheMaxLabel.sizePolicy().hasHeightForWidth())
        self.gdalCacheMaxLabel.setSizePolicy(sizePolicy)
        self.gdalCacheMaxLabel.setText(QtGui.QApplication.translate("gdalInfoWidget", "Cache Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalCacheMaxLabel.setObjectName(_fromUtf8("gdalCacheMaxLabel"))
        self.cacheGridLayout.addWidget(self.gdalCacheMaxLabel, 0, 0, 1, 1)
        self.gdalCacheMaxValue = QtGui.QLabel(self.gdalCacheGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalCacheMaxValue.sizePolicy().hasHeightForWidth())
        self.gdalCacheMaxValue.setSizePolicy(sizePolicy)
        self.gdalCacheMaxValue.setSizeIncrement(QtCore.QSize(1, 0))
        self.gdalCacheMaxValue.setText(QtGui.QApplication.translate("gdalInfoWidget", "max cache value", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalCacheMaxValue.setObjectName(_fromUtf8("gdalCacheMaxValue"))
        self.cacheGridLayout.addWidget(self.gdalCacheMaxValue, 0, 1, 1, 1)
        self.gdalCacheUsedLabel = QtGui.QLabel(self.gdalCacheGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalCacheUsedLabel.sizePolicy().hasHeightForWidth())
        self.gdalCacheUsedLabel.setSizePolicy(sizePolicy)
        self.gdalCacheUsedLabel.setText(QtGui.QApplication.translate("gdalInfoWidget", "Cache Used:", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalCacheUsedLabel.setObjectName(_fromUtf8("gdalCacheUsedLabel"))
        self.cacheGridLayout.addWidget(self.gdalCacheUsedLabel, 1, 0, 1, 1)
        self.gdalCacheUsedValue = QtGui.QLabel(self.gdalCacheGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalCacheUsedValue.sizePolicy().hasHeightForWidth())
        self.gdalCacheUsedValue.setSizePolicy(sizePolicy)
        self.gdalCacheUsedValue.setSizeIncrement(QtCore.QSize(1, 0))
        self.gdalCacheUsedValue.setText(QtGui.QApplication.translate("gdalInfoWidget", "used cache value", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalCacheUsedValue.setObjectName(_fromUtf8("gdalCacheUsedValue"))
        self.cacheGridLayout.addWidget(self.gdalCacheUsedValue, 1, 1, 1, 1)
        self.gdalHorizontalLayout.addWidget(self.gdalCacheGroupBox)
        self.verticalLayout.addLayout(self.gdalHorizontalLayout)
        self.gdalDriversGroupBox = QtGui.QGroupBox(gdalInfoWidget)
        self.gdalDriversGroupBox.setTitle(QtGui.QApplication.translate("gdalInfoWidget", "Available Drivers", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversGroupBox.setObjectName(_fromUtf8("gdalDriversGroupBox"))
        self.driversVerticalLayout = QtGui.QVBoxLayout(self.gdalDriversGroupBox)
        self.driversVerticalLayout.setObjectName(_fromUtf8("driversVerticalLayout"))
        self.gdalDriverHorizontalLayout = QtGui.QHBoxLayout()
        self.gdalDriverHorizontalLayout.setObjectName(_fromUtf8("gdalDriverHorizontalLayout"))
        self.gdalDriversNumLabel = QtGui.QLabel(self.gdalDriversGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalDriversNumLabel.sizePolicy().hasHeightForWidth())
        self.gdalDriversNumLabel.setSizePolicy(sizePolicy)
        self.gdalDriversNumLabel.setText(QtGui.QApplication.translate("gdalInfoWidget", "Number of available drivers:", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversNumLabel.setObjectName(_fromUtf8("gdalDriversNumLabel"))
        self.gdalDriverHorizontalLayout.addWidget(self.gdalDriversNumLabel)
        self.gdalDriversNumValue = QtGui.QLabel(self.gdalDriversGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdalDriversNumValue.sizePolicy().hasHeightForWidth())
        self.gdalDriversNumValue.setSizePolicy(sizePolicy)
        self.gdalDriversNumValue.setSizeIncrement(QtCore.QSize(1, 0))
        self.gdalDriversNumValue.setText(QtGui.QApplication.translate("gdalInfoWidget", "number of drivers", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversNumValue.setObjectName(_fromUtf8("gdalDriversNumValue"))
        self.gdalDriverHorizontalLayout.addWidget(self.gdalDriversNumValue)
        self.driversVerticalLayout.addLayout(self.gdalDriverHorizontalLayout)
        self.gdalDriversTableWidget = QtGui.QTableWidget(self.gdalDriversGroupBox)
        self.gdalDriversTableWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.gdalDriversTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.gdalDriversTableWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.gdalDriversTableWidget.setObjectName(_fromUtf8("gdalDriversTableWidget"))
        self.gdalDriversTableWidget.setColumnCount(9)
        self.gdalDriversTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("gdalInfoWidget", "Short Name", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("gdalInfoWidget", "Long Name", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("gdalInfoWidget", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("gdalInfoWidget", "Help Topic", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("gdalInfoWidget", "Extension", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("gdalInfoWidget", "Mime Type", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("gdalInfoWidget", "Creation Data Types", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversTableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("gdalInfoWidget", "Creation Option List", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversTableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("gdalInfoWidget", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.gdalDriversTableWidget.setHorizontalHeaderItem(8, item)
        self.gdalDriversTableWidget.horizontalHeader().setStretchLastSection(True)
        self.driversVerticalLayout.addWidget(self.gdalDriversTableWidget)
        self.verticalLayout.addWidget(self.gdalDriversGroupBox)

        self.retranslateUi(gdalInfoWidget)
        QtCore.QMetaObject.connectSlotsByName(gdalInfoWidget)

    def retranslateUi(self, gdalInfoWidget):
        self.gdalDriversTableWidget.setSortingEnabled(True)
        item = self.gdalDriversTableWidget.horizontalHeaderItem(0)
        item = self.gdalDriversTableWidget.horizontalHeaderItem(1)
        item = self.gdalDriversTableWidget.horizontalHeaderItem(2)
        item = self.gdalDriversTableWidget.horizontalHeaderItem(3)
        item = self.gdalDriversTableWidget.horizontalHeaderItem(4)
        item = self.gdalDriversTableWidget.horizontalHeaderItem(5)
        item = self.gdalDriversTableWidget.horizontalHeaderItem(6)
        item = self.gdalDriversTableWidget.horizontalHeaderItem(7)
        item = self.gdalDriversTableWidget.horizontalHeaderItem(8)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    gdalInfoWidget = QtGui.QWidget()
    ui = Ui_gdalInfoWidget()
    ui.setupUi(gdalInfoWidget)
    gdalInfoWidget.show()
    sys.exit(app.exec_())

