# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gsdview/gdalbackend/ui/overview.ui'
#
# Created: Sun Nov 13 21:17:58 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_overviewTab(object):
    def setupUi(self, overviewTab):
        overviewTab.setObjectName(_fromUtf8("overviewTab"))
        overviewTab.resize(529, 456)
        overviewTab.setWindowTitle(QtGui.QApplication.translate("overviewTab", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout = QtGui.QHBoxLayout(overviewTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.infoGroupBox = QtGui.QGroupBox(overviewTab)
        self.infoGroupBox.setTitle(QtGui.QApplication.translate("overviewTab", "Overview Info", None, QtGui.QApplication.UnicodeUTF8))
        self.infoGroupBox.setObjectName(_fromUtf8("infoGroupBox"))
        self.infoFormLayout = QtGui.QFormLayout(self.infoGroupBox)
        self.infoFormLayout.setObjectName(_fromUtf8("infoFormLayout"))
        self.overviewCountLabel = QtGui.QLabel(self.infoGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overviewCountLabel.sizePolicy().hasHeightForWidth())
        self.overviewCountLabel.setSizePolicy(sizePolicy)
        self.overviewCountLabel.setText(QtGui.QApplication.translate("overviewTab", "Overview Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.overviewCountLabel.setObjectName(_fromUtf8("overviewCountLabel"))
        self.infoFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.overviewCountLabel)
        self.overviewCountValue = QtGui.QLabel(self.infoGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overviewCountValue.sizePolicy().hasHeightForWidth())
        self.overviewCountValue.setSizePolicy(sizePolicy)
        self.overviewCountValue.setText(QtGui.QApplication.translate("overviewTab", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.overviewCountValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.overviewCountValue.setObjectName(_fromUtf8("overviewCountValue"))
        self.infoFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.overviewCountValue)
        self.hasArbitraryOverviewsLabel = QtGui.QLabel(self.infoGroupBox)
        self.hasArbitraryOverviewsLabel.setText(QtGui.QApplication.translate("overviewTab", "Has Arbitrary Overviews:", None, QtGui.QApplication.UnicodeUTF8))
        self.hasArbitraryOverviewsLabel.setObjectName(_fromUtf8("hasArbitraryOverviewsLabel"))
        self.infoFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.hasArbitraryOverviewsLabel)
        self.hasArbitraryOverviewsValue = QtGui.QLabel(self.infoGroupBox)
        self.hasArbitraryOverviewsValue.setText(QtGui.QApplication.translate("overviewTab", "no", None, QtGui.QApplication.UnicodeUTF8))
        self.hasArbitraryOverviewsValue.setObjectName(_fromUtf8("hasArbitraryOverviewsValue"))
        self.infoFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.hasArbitraryOverviewsValue)
        self.fullSizeLabel = QtGui.QLabel(self.infoGroupBox)
        self.fullSizeLabel.setText(QtGui.QApplication.translate("overviewTab", "Full Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fullSizeLabel.setObjectName(_fromUtf8("fullSizeLabel"))
        self.infoFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.fullSizeLabel)
        self.fullSizeValue = QtGui.QLabel(self.infoGroupBox)
        self.fullSizeValue.setText(QtGui.QApplication.translate("overviewTab", "nrows x ncols", None, QtGui.QApplication.UnicodeUTF8))
        self.fullSizeValue.setObjectName(_fromUtf8("fullSizeValue"))
        self.infoFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.fullSizeValue)
        self.verticalLayout.addWidget(self.infoGroupBox)
        self.optionsGroupBox = QtGui.QGroupBox(overviewTab)
        self.optionsGroupBox.setTitle(QtGui.QApplication.translate("overviewTab", "Computation Options", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsGroupBox.setObjectName(_fromUtf8("optionsGroupBox"))
        self.optionsVerticalLayout = QtGui.QVBoxLayout(self.optionsGroupBox)
        self.optionsVerticalLayout.setObjectName(_fromUtf8("optionsVerticalLayout"))
        self.optionsFormLayout = QtGui.QFormLayout()
        self.optionsFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.optionsFormLayout.setObjectName(_fromUtf8("optionsFormLayout"))
        self.resamplingMethodLabel = QtGui.QLabel(self.optionsGroupBox)
        self.resamplingMethodLabel.setText(QtGui.QApplication.translate("overviewTab", "Resampling method", None, QtGui.QApplication.UnicodeUTF8))
        self.resamplingMethodLabel.setObjectName(_fromUtf8("resamplingMethodLabel"))
        self.optionsFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.resamplingMethodLabel)
        self.resamplingMethodComboBox = QtGui.QComboBox(self.optionsGroupBox)
        self.resamplingMethodComboBox.setObjectName(_fromUtf8("resamplingMethodComboBox"))
        self.resamplingMethodComboBox.addItem(_fromUtf8(""))
        self.resamplingMethodComboBox.setItemText(0, QtGui.QApplication.translate("overviewTab", "DEFAULT", None, QtGui.QApplication.UnicodeUTF8))
        self.resamplingMethodComboBox.addItem(_fromUtf8(""))
        self.resamplingMethodComboBox.setItemText(1, QtGui.QApplication.translate("overviewTab", "nearest", None, QtGui.QApplication.UnicodeUTF8))
        self.resamplingMethodComboBox.addItem(_fromUtf8(""))
        self.resamplingMethodComboBox.setItemText(2, QtGui.QApplication.translate("overviewTab", "average", None, QtGui.QApplication.UnicodeUTF8))
        self.resamplingMethodComboBox.addItem(_fromUtf8(""))
        self.resamplingMethodComboBox.setItemText(3, QtGui.QApplication.translate("overviewTab", "gauss", None, QtGui.QApplication.UnicodeUTF8))
        self.resamplingMethodComboBox.addItem(_fromUtf8(""))
        self.resamplingMethodComboBox.setItemText(4, QtGui.QApplication.translate("overviewTab", "cubic", None, QtGui.QApplication.UnicodeUTF8))
        self.resamplingMethodComboBox.addItem(_fromUtf8(""))
        self.resamplingMethodComboBox.setItemText(5, QtGui.QApplication.translate("overviewTab", "average_mp", None, QtGui.QApplication.UnicodeUTF8))
        self.resamplingMethodComboBox.addItem(_fromUtf8(""))
        self.resamplingMethodComboBox.setItemText(6, QtGui.QApplication.translate("overviewTab", "average_magphase", None, QtGui.QApplication.UnicodeUTF8))
        self.resamplingMethodComboBox.addItem(_fromUtf8(""))
        self.resamplingMethodComboBox.setItemText(7, QtGui.QApplication.translate("overviewTab", "mode", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.resamplingMethodComboBox)
        self.readonlyLabel = QtGui.QLabel(self.optionsGroupBox)
        self.readonlyLabel.setToolTip(QtGui.QApplication.translate("overviewTab", "Open target dataset in read-only mode.", None, QtGui.QApplication.UnicodeUTF8))
        self.readonlyLabel.setText(QtGui.QApplication.translate("overviewTab", "Read only", None, QtGui.QApplication.UnicodeUTF8))
        self.readonlyLabel.setObjectName(_fromUtf8("readonlyLabel"))
        self.optionsFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.readonlyLabel)
        self.readonlyCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.readonlyCheckBox.setToolTip(QtGui.QApplication.translate("overviewTab", "Open target dataset in read-only mode.", None, QtGui.QApplication.UnicodeUTF8))
        self.readonlyCheckBox.setText(_fromUtf8(""))
        self.readonlyCheckBox.setObjectName(_fromUtf8("readonlyCheckBox"))
        self.optionsFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.readonlyCheckBox)
        self.compressionLabel = QtGui.QLabel(self.optionsGroupBox)
        self.compressionLabel.setToolTip(QtGui.QApplication.translate("overviewTab", "Set the conpression mode for TIFF overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionLabel.setText(QtGui.QApplication.translate("overviewTab", "Compression", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionLabel.setObjectName(_fromUtf8("compressionLabel"))
        self.optionsFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.compressionLabel)
        self.compressionComboBox = QtGui.QComboBox(self.optionsGroupBox)
        self.compressionComboBox.setToolTip(QtGui.QApplication.translate("overviewTab", "Set the conpression mode for TIFF overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionComboBox.setObjectName(_fromUtf8("compressionComboBox"))
        self.compressionComboBox.addItem(_fromUtf8(""))
        self.compressionComboBox.setItemText(0, QtGui.QApplication.translate("overviewTab", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionComboBox.addItem(_fromUtf8(""))
        self.compressionComboBox.setItemText(1, QtGui.QApplication.translate("overviewTab", "DEFLATE", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionComboBox.addItem(_fromUtf8(""))
        self.compressionComboBox.setItemText(2, QtGui.QApplication.translate("overviewTab", "JPEG", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionComboBox.addItem(_fromUtf8(""))
        self.compressionComboBox.setItemText(3, QtGui.QApplication.translate("overviewTab", "LZW", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionComboBox.addItem(_fromUtf8(""))
        self.compressionComboBox.setItemText(4, QtGui.QApplication.translate("overviewTab", "PACKBITS", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.compressionComboBox)
        self.photointLabel = QtGui.QLabel(self.optionsGroupBox)
        self.photointLabel.setToolTip(QtGui.QApplication.translate("overviewTab", "Set the photometdic interpretation mode for TIFF overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.photointLabel.setText(QtGui.QApplication.translate("overviewTab", "Photoint", None, QtGui.QApplication.UnicodeUTF8))
        self.photointLabel.setObjectName(_fromUtf8("photointLabel"))
        self.optionsFormLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.photointLabel)
        self.photointComboBox = QtGui.QComboBox(self.optionsGroupBox)
        self.photointComboBox.setToolTip(QtGui.QApplication.translate("overviewTab", "Set the photometdic interpretation mode for TIFF overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.photointComboBox.setEditable(True)
        self.photointComboBox.setObjectName(_fromUtf8("photointComboBox"))
        self.photointComboBox.addItem(_fromUtf8(""))
        self.photointComboBox.setItemText(0, QtGui.QApplication.translate("overviewTab", "DEFAULT", None, QtGui.QApplication.UnicodeUTF8))
        self.photointComboBox.addItem(_fromUtf8(""))
        self.photointComboBox.setItemText(1, QtGui.QApplication.translate("overviewTab", "RGB", None, QtGui.QApplication.UnicodeUTF8))
        self.photointComboBox.addItem(_fromUtf8(""))
        self.photointComboBox.setItemText(2, QtGui.QApplication.translate("overviewTab", "YCBCR", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsFormLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.photointComboBox)
        self.interleavingLabel = QtGui.QLabel(self.optionsGroupBox)
        self.interleavingLabel.setToolTip(QtGui.QApplication.translate("overviewTab", "Set the ovetvire interleaving method for TIFF overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.interleavingLabel.setText(QtGui.QApplication.translate("overviewTab", "Interleaving", None, QtGui.QApplication.UnicodeUTF8))
        self.interleavingLabel.setObjectName(_fromUtf8("interleavingLabel"))
        self.optionsFormLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.interleavingLabel)
        self.interleavingComboBox = QtGui.QComboBox(self.optionsGroupBox)
        self.interleavingComboBox.setToolTip(QtGui.QApplication.translate("overviewTab", "Set the ovetvire interleaving method for TIFF overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.interleavingComboBox.setObjectName(_fromUtf8("interleavingComboBox"))
        self.interleavingComboBox.addItem(_fromUtf8(""))
        self.interleavingComboBox.setItemText(0, QtGui.QApplication.translate("overviewTab", "DEFAULT", None, QtGui.QApplication.UnicodeUTF8))
        self.interleavingComboBox.addItem(_fromUtf8(""))
        self.interleavingComboBox.setItemText(1, QtGui.QApplication.translate("overviewTab", "PIXEL", None, QtGui.QApplication.UnicodeUTF8))
        self.interleavingComboBox.addItem(_fromUtf8(""))
        self.interleavingComboBox.setItemText(2, QtGui.QApplication.translate("overviewTab", "BAND", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsFormLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.interleavingComboBox)
        self.bigtiffLabel = QtGui.QLabel(self.optionsGroupBox)
        self.bigtiffLabel.setText(QtGui.QApplication.translate("overviewTab", "Use Big TIFF", None, QtGui.QApplication.UnicodeUTF8))
        self.bigtiffLabel.setObjectName(_fromUtf8("bigtiffLabel"))
        self.optionsFormLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.bigtiffLabel)
        self.bigtiffComboBox = QtGui.QComboBox(self.optionsGroupBox)
        self.bigtiffComboBox.setObjectName(_fromUtf8("bigtiffComboBox"))
        self.bigtiffComboBox.addItem(_fromUtf8(""))
        self.bigtiffComboBox.setItemText(0, QtGui.QApplication.translate("overviewTab", "DEFAULT", None, QtGui.QApplication.UnicodeUTF8))
        self.bigtiffComboBox.addItem(_fromUtf8(""))
        self.bigtiffComboBox.setItemText(1, QtGui.QApplication.translate("overviewTab", "YES", None, QtGui.QApplication.UnicodeUTF8))
        self.bigtiffComboBox.addItem(_fromUtf8(""))
        self.bigtiffComboBox.setItemText(2, QtGui.QApplication.translate("overviewTab", "NO", None, QtGui.QApplication.UnicodeUTF8))
        self.bigtiffComboBox.addItem(_fromUtf8(""))
        self.bigtiffComboBox.setItemText(3, QtGui.QApplication.translate("overviewTab", "IF_NEEDED", None, QtGui.QApplication.UnicodeUTF8))
        self.bigtiffComboBox.addItem(_fromUtf8(""))
        self.bigtiffComboBox.setItemText(4, QtGui.QApplication.translate("overviewTab", "IF_SAFER", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsFormLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.bigtiffComboBox)
        self.rrdLabel = QtGui.QLabel(self.optionsGroupBox)
        self.rrdLabel.setToolTip(QtGui.QApplication.translate("overviewTab", "Use Erdas imagine format for overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.rrdLabel.setText(QtGui.QApplication.translate("overviewTab", "Use RRD", None, QtGui.QApplication.UnicodeUTF8))
        self.rrdLabel.setObjectName(_fromUtf8("rrdLabel"))
        self.optionsFormLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.rrdLabel)
        self.rrdCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.rrdCheckBox.setToolTip(QtGui.QApplication.translate("overviewTab", "Use Erdas imagine format for overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.rrdCheckBox.setText(_fromUtf8(""))
        self.rrdCheckBox.setObjectName(_fromUtf8("rrdCheckBox"))
        self.optionsFormLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.rrdCheckBox)
        self.recomputeLabel = QtGui.QLabel(self.optionsGroupBox)
        self.recomputeLabel.setToolTip(QtGui.QApplication.translate("overviewTab", "Also re-compute exixting overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.recomputeLabel.setText(QtGui.QApplication.translate("overviewTab", "Recompute all", None, QtGui.QApplication.UnicodeUTF8))
        self.recomputeLabel.setObjectName(_fromUtf8("recomputeLabel"))
        self.optionsFormLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.recomputeLabel)
        self.recomputeCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.recomputeCheckBox.setToolTip(QtGui.QApplication.translate("overviewTab", "Also re-compute exixting overviews.", None, QtGui.QApplication.UnicodeUTF8))
        self.recomputeCheckBox.setText(_fromUtf8(""))
        self.recomputeCheckBox.setObjectName(_fromUtf8("recomputeCheckBox"))
        self.optionsFormLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.recomputeCheckBox)
        self.optionsVerticalLayout.addLayout(self.optionsFormLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.optionsVerticalLayout.addItem(spacerItem)
        self.startButton = QtGui.QPushButton(self.optionsGroupBox)
        self.startButton.setEnabled(False)
        self.startButton.setText(QtGui.QApplication.translate("overviewTab", "Start Computation", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.optionsVerticalLayout.addWidget(self.startButton)
        self.verticalLayout.addWidget(self.optionsGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.ovrListGroupBox = QtGui.QGroupBox(overviewTab)
        self.ovrListGroupBox.setTitle(QtGui.QApplication.translate("overviewTab", "Available Overviews", None, QtGui.QApplication.UnicodeUTF8))
        self.ovrListGroupBox.setObjectName(_fromUtf8("ovrListGroupBox"))
        self.ovrListVerticalLayout = QtGui.QVBoxLayout(self.ovrListGroupBox)
        self.ovrListVerticalLayout.setObjectName(_fromUtf8("ovrListVerticalLayout"))
        self.ovrTreeView = QtGui.QTreeView(self.ovrListGroupBox)
        self.ovrTreeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.ovrTreeView.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.ovrTreeView.setIndentation(0)
        self.ovrTreeView.setObjectName(_fromUtf8("ovrTreeView"))
        self.ovrTreeView.header().setVisible(False)
        self.ovrListVerticalLayout.addWidget(self.ovrTreeView)
        self.addlevelHorizontalLayout = QtGui.QHBoxLayout()
        self.addlevelHorizontalLayout.setObjectName(_fromUtf8("addlevelHorizontalLayout"))
        self.addLevelSpinBox = QtGui.QSpinBox(self.ovrListGroupBox)
        self.addLevelSpinBox.setMinimum(1)
        self.addLevelSpinBox.setObjectName(_fromUtf8("addLevelSpinBox"))
        self.addlevelHorizontalLayout.addWidget(self.addLevelSpinBox)
        self.addLevelButton = QtGui.QPushButton(self.ovrListGroupBox)
        self.addLevelButton.setText(QtGui.QApplication.translate("overviewTab", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.addLevelButton.setObjectName(_fromUtf8("addLevelButton"))
        self.addlevelHorizontalLayout.addWidget(self.addLevelButton)
        self.ovrListVerticalLayout.addLayout(self.addlevelHorizontalLayout)
        self.horizontalLayout.addWidget(self.ovrListGroupBox)

        self.retranslateUi(overviewTab)
        self.resamplingMethodComboBox.setCurrentIndex(2)
        QtCore.QObject.connect(self.rrdCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.compressionLabel.setDisabled)
        QtCore.QObject.connect(self.rrdCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.compressionComboBox.setDisabled)
        QtCore.QObject.connect(self.rrdCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.photointLabel.setDisabled)
        QtCore.QObject.connect(self.rrdCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.photointComboBox.setDisabled)
        QtCore.QObject.connect(self.rrdCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.interleavingLabel.setDisabled)
        QtCore.QObject.connect(self.rrdCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.interleavingComboBox.setDisabled)
        QtCore.QObject.connect(self.rrdCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.bigtiffLabel.setDisabled)
        QtCore.QObject.connect(self.rrdCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.bigtiffComboBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(overviewTab)

    def retranslateUi(self, overviewTab):
        pass


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    overviewTab = QtGui.QWidget()
    ui = Ui_overviewTab()
    ui.setupUi(overviewTab)
    overviewTab.show()
    sys.exit(app.exec_())

